/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminCoursesRouteImport } from './routes/_authenticated/admin/courses'
import { Route as AuthenticatedAdminQuestionsRouteImport } from './routes/_authenticated/admin/questions'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedCoursesCourseIdRouteImport } from './routes/_authenticated/courses.$courseId'
import { Route as AuthenticatedLearnIndexRouteImport } from './routes/_authenticated/learn/index'
import { Route as AuthenticatedLearnSubtopicIdRouteImport } from './routes/_authenticated/learn.$subtopicId'
import { Route as AuthenticatedQuizSetupRouteImport } from './routes/_authenticated/quiz.setup'
import { Route as AuthenticatedSimulateSetupRouteImport } from './routes/_authenticated/simulate.setup'
import { Route as AuthenticatedLearnCourseCourseIdRouteImport } from './routes/_authenticated/learn/course.$courseId'
import { Route as AuthenticatedQuizResultsAttemptIdRouteImport } from './routes/_authenticated/quiz.results.$attemptId'
import { Route as AuthenticatedQuizRunAttemptIdRouteImport } from './routes/_authenticated/quiz.run.$attemptId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminCoursesRoute =
  AuthenticatedAdminCoursesRouteImport.update({
    id: '/courses',
    path: '/courses',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminQuestionsRoute =
  AuthenticatedAdminQuestionsRouteImport.update({
    id: '/questions',
    path: '/questions',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedCoursesCourseIdRoute =
  AuthenticatedCoursesCourseIdRouteImport.update({
    id: '/courses/$courseId',
    path: '/courses/$courseId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLearnIndexRoute = AuthenticatedLearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLearnSubtopicIdRoute =
  AuthenticatedLearnSubtopicIdRouteImport.update({
    id: '/learn/$subtopicId',
    path: '/learn/$subtopicId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuizSetupRoute = AuthenticatedQuizSetupRouteImport.update({
  id: '/quiz/setup',
  path: '/quiz/setup',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSimulateSetupRoute =
  AuthenticatedSimulateSetupRouteImport.update({
    id: '/simulate/setup',
    path: '/simulate/setup',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLearnCourseCourseIdRoute =
  AuthenticatedLearnCourseCourseIdRouteImport.update({
    id: '/learn/course/$courseId',
    path: '/learn/course/$courseId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuizResultsAttemptIdRoute =
  AuthenticatedQuizResultsAttemptIdRouteImport.update({
    id: '/quiz/results/$attemptId',
    path: '/quiz/results/$attemptId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuizRunAttemptIdRoute =
  AuthenticatedQuizRunAttemptIdRouteImport.update({
    id: '/quiz/run/$attemptId',
    path: '/quiz/run/$attemptId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/admin/questions': typeof AuthenticatedAdminQuestionsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/courses/$courseId': typeof AuthenticatedCoursesCourseIdRoute
  '/learn/$subtopicId': typeof AuthenticatedLearnSubtopicIdRoute
  '/quiz/setup': typeof AuthenticatedQuizSetupRoute
  '/simulate/setup': typeof AuthenticatedSimulateSetupRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/learn/': typeof AuthenticatedLearnIndexRoute
  '/learn/course/$courseId': typeof AuthenticatedLearnCourseCourseIdRoute
  '/quiz/results/$attemptId': typeof AuthenticatedQuizResultsAttemptIdRoute
  '/quiz/run/$attemptId': typeof AuthenticatedQuizRunAttemptIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/admin/questions': typeof AuthenticatedAdminQuestionsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/courses/$courseId': typeof AuthenticatedCoursesCourseIdRoute
  '/learn/$subtopicId': typeof AuthenticatedLearnSubtopicIdRoute
  '/quiz/setup': typeof AuthenticatedQuizSetupRoute
  '/simulate/setup': typeof AuthenticatedSimulateSetupRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/learn': typeof AuthenticatedLearnIndexRoute
  '/learn/course/$courseId': typeof AuthenticatedLearnCourseCourseIdRoute
  '/quiz/results/$attemptId': typeof AuthenticatedQuizResultsAttemptIdRoute
  '/quiz/run/$attemptId': typeof AuthenticatedQuizRunAttemptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/_authenticated/admin/questions': typeof AuthenticatedAdminQuestionsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/courses/$courseId': typeof AuthenticatedCoursesCourseIdRoute
  '/_authenticated/learn/$subtopicId': typeof AuthenticatedLearnSubtopicIdRoute
  '/_authenticated/quiz/setup': typeof AuthenticatedQuizSetupRoute
  '/_authenticated/simulate/setup': typeof AuthenticatedSimulateSetupRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/learn/': typeof AuthenticatedLearnIndexRoute
  '/_authenticated/learn/course/$courseId': typeof AuthenticatedLearnCourseCourseIdRoute
  '/_authenticated/quiz/results/$attemptId': typeof AuthenticatedQuizResultsAttemptIdRoute
  '/_authenticated/quiz/run/$attemptId': typeof AuthenticatedQuizRunAttemptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/admin'
    | '/dashboard'
    | '/history'
    | '/leaderboard'
    | '/onboarding'
    | '/admin/courses'
    | '/admin/questions'
    | '/admin/users'
    | '/courses/$courseId'
    | '/learn/$subtopicId'
    | '/quiz/setup'
    | '/simulate/setup'
    | '/admin/'
    | '/learn/'
    | '/learn/course/$courseId'
    | '/quiz/results/$attemptId'
    | '/quiz/run/$attemptId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/dashboard'
    | '/history'
    | '/leaderboard'
    | '/onboarding'
    | '/admin/courses'
    | '/admin/questions'
    | '/admin/users'
    | '/courses/$courseId'
    | '/learn/$subtopicId'
    | '/quiz/setup'
    | '/simulate/setup'
    | '/admin'
    | '/learn'
    | '/learn/course/$courseId'
    | '/quiz/results/$attemptId'
    | '/quiz/run/$attemptId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/history'
    | '/_authenticated/leaderboard'
    | '/_authenticated/onboarding'
    | '/_authenticated/admin/courses'
    | '/_authenticated/admin/questions'
    | '/_authenticated/admin/users'
    | '/_authenticated/courses/$courseId'
    | '/_authenticated/learn/$subtopicId'
    | '/_authenticated/quiz/setup'
    | '/_authenticated/simulate/setup'
    | '/_authenticated/admin/'
    | '/_authenticated/learn/'
    | '/_authenticated/learn/course/$courseId'
    | '/_authenticated/quiz/results/$attemptId'
    | '/_authenticated/quiz/run/$attemptId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/courses': {
      id: '/_authenticated/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AuthenticatedAdminCoursesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/questions': {
      id: '/_authenticated/admin/questions'
      path: '/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof AuthenticatedAdminQuestionsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/courses/$courseId': {
      id: '/_authenticated/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof AuthenticatedCoursesCourseIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learn/': {
      id: '/_authenticated/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof AuthenticatedLearnIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learn/$subtopicId': {
      id: '/_authenticated/learn/$subtopicId'
      path: '/learn/$subtopicId'
      fullPath: '/learn/$subtopicId'
      preLoaderRoute: typeof AuthenticatedLearnSubtopicIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quiz/setup': {
      id: '/_authenticated/quiz/setup'
      path: '/quiz/setup'
      fullPath: '/quiz/setup'
      preLoaderRoute: typeof AuthenticatedQuizSetupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/simulate/setup': {
      id: '/_authenticated/simulate/setup'
      path: '/simulate/setup'
      fullPath: '/simulate/setup'
      preLoaderRoute: typeof AuthenticatedSimulateSetupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learn/course/$courseId': {
      id: '/_authenticated/learn/course/$courseId'
      path: '/learn/course/$courseId'
      fullPath: '/learn/course/$courseId'
      preLoaderRoute: typeof AuthenticatedLearnCourseCourseIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quiz/results/$attemptId': {
      id: '/_authenticated/quiz/results/$attemptId'
      path: '/quiz/results/$attemptId'
      fullPath: '/quiz/results/$attemptId'
      preLoaderRoute: typeof AuthenticatedQuizResultsAttemptIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quiz/run/$attemptId': {
      id: '/_authenticated/quiz/run/$attemptId'
      path: '/quiz/run/$attemptId'
      fullPath: '/quiz/run/$attemptId'
      preLoaderRoute: typeof AuthenticatedQuizRunAttemptIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminCoursesRoute: typeof AuthenticatedAdminCoursesRoute
  AuthenticatedAdminQuestionsRoute: typeof AuthenticatedAdminQuestionsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminCoursesRoute: AuthenticatedAdminCoursesRoute,
    AuthenticatedAdminQuestionsRoute: AuthenticatedAdminQuestionsRoute,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedCoursesCourseIdRoute: typeof AuthenticatedCoursesCourseIdRoute
  AuthenticatedLearnSubtopicIdRoute: typeof AuthenticatedLearnSubtopicIdRoute
  AuthenticatedQuizSetupRoute: typeof AuthenticatedQuizSetupRoute
  AuthenticatedSimulateSetupRoute: typeof AuthenticatedSimulateSetupRoute
  AuthenticatedLearnIndexRoute: typeof AuthenticatedLearnIndexRoute
  AuthenticatedLearnCourseCourseIdRoute: typeof AuthenticatedLearnCourseCourseIdRoute
  AuthenticatedQuizResultsAttemptIdRoute: typeof AuthenticatedQuizResultsAttemptIdRoute
  AuthenticatedQuizRunAttemptIdRoute: typeof AuthenticatedQuizRunAttemptIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedCoursesCourseIdRoute: AuthenticatedCoursesCourseIdRoute,
  AuthenticatedLearnSubtopicIdRoute: AuthenticatedLearnSubtopicIdRoute,
  AuthenticatedQuizSetupRoute: AuthenticatedQuizSetupRoute,
  AuthenticatedSimulateSetupRoute: AuthenticatedSimulateSetupRoute,
  AuthenticatedLearnIndexRoute: AuthenticatedLearnIndexRoute,
  AuthenticatedLearnCourseCourseIdRoute: AuthenticatedLearnCourseCourseIdRoute,
  AuthenticatedQuizResultsAttemptIdRoute:
    AuthenticatedQuizResultsAttemptIdRoute,
  AuthenticatedQuizRunAttemptIdRoute: AuthenticatedQuizRunAttemptIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
