-- Seed SQL for 4 PDF courses (158 Total Questions)

-- 1. Oracle AI Agent Studio
DO $$
DECLARE
  c_id UUID;
  s1 UUID; s2 UUID; s3 UUID; s4 UUID;
BEGIN
  INSERT INTO public.courses (name, description, icon)
  VALUES ('Oracle AI Agent Studio', 'Comprehensive assessment for building AI agents, multi-agent workflows, tools, and RAG in Oracle Fusion Applications.', 'bot')
  RETURNING id INTO c_id;

  INSERT INTO public.subtopics (course_id, name, order_index) VALUES (c_id, 'Agent Architecture & Fundamentals', 1) RETURNING id INTO s1;
  INSERT INTO public.subtopics (course_id, name, order_index) VALUES (c_id, 'Workflow Nodes & Orchestration', 2) RETURNING id INTO s2;
  INSERT INTO public.subtopics (course_id, name, order_index) VALUES (c_id, 'Tools & Integrations', 3) RETURNING id INTO s3;
  INSERT INTO public.subtopics (course_id, name, order_index) VALUES (c_id, 'Evaluations, Security & RAG Metrics', 4) RETURNING id INTO s4;

  -- Questions for s1
  INSERT INTO public.questions (subtopic_id, type, question_text, options, correct_answers, explanation, difficulty) VALUES
  (s1, 'mcq', 'When is a multi-agent (with Supervisor agent) configuration most appropriate?', '["When editing static HTML pages", "When the workflow is complex, modular, or requires domain specialization", "When the task is a simple request with no dependencies", "For increasing token usage only"]'::jsonb, '[1]'::jsonb, 'Correct.', 'medium'),
  (s1, 'mcq', 'What is a primary advantage of Workflow Agents over traditional workflow engines?', '["They only execute static, linear tasks.", "They halt at every exception for user intervention.", "They can reason, adapt, and improve over time.", "They require all logic to be hard-coded in advance."]'::jsonb, '[2]'::jsonb, 'Correct.', 'medium'),
  (s1, 'mcq', 'Which of these best helps reduce hallucinations in AI Agent responses?', '["Running more hardware diagnostics", "Dynamic grounding through RAG with relevant documents", "Increasing prompt length", "Allowing access to all system data"]'::jsonb, '[1]'::jsonb, 'Correct.', 'medium'),
  (s1, 'mcq', 'Which feature ensures AI Agents only access data permitted to the user?', '["Role-based access control", "Prompt-length limitation", "Open API templates", "External plugin modules"]'::jsonb, '[0]'::jsonb, 'Correct.', 'medium'),
  (s1, 'mcq', 'Which agent component is described as being reusable, focused on a specific subject area, and aligning agent responses to certain themes?', '["Document Tool", "Supervisor agent", "Credential Store", "Topic"]'::jsonb, '[3]'::jsonb, 'Correct.', 'medium'),
  (s1, 'mcq', 'Which statement accurately describes Business Objects in AI Agent Studio?', '["They allow for text and image upload into Fusion apps.", "They act as placeholders for user interface changes.", "They are used for end user authentication and custom layout for Fusion apps.", "They provide a structure for agents to interact with Fusion data and APIs."]'::jsonb, '[3]'::jsonb, 'Correct.', 'medium');

  -- Questions for s2
  INSERT INTO public.questions (subtopic_id, type, question_text, options, correct_answers, explanation, difficulty) VALUES
  (s2, 'mcq', 'If you need to route your workflow to multiple possible paths based on complex conditions, which node is most suitable?', '["Switch Node", "Human Approval Node", "Set Variables Node", "Loop Node"]'::jsonb, '[0]'::jsonb, 'Correct.', 'medium'),
  (s2, 'mcq', 'What is the main function of the workflow node in a workflow agent?', '["Sends email notifications", "Calls an external API", "Runs another workflow as a subflow", "Pauses execution for human approval"]'::jsonb, '[2]'::jsonb, 'Correct.', 'medium'),
  (s2, 'mcq', 'If you need to pause the workflow agent and get a decision from a user before proceeding, which node would you choose?', '["Loop Node", "Human Approval Node", "If Condition Node", "Parallel Node"]'::jsonb, '[1]'::jsonb, 'Correct.', 'medium'),
  (s2, 'mcq', 'Which question should you ask when deciding on orchestration patterns for your workflow agents?', '["Is the workflow only for document upload tasks?", "Who will manually execute every workflow branch?", "Does the workflow need advanced graphics capabilities?", "Do I need Chaining, Switch, Parallel, Iteration, or Looping patterns?"]'::jsonb, '[3]'::jsonb, 'Correct.', 'medium'),
  (s2, 'mcq', 'What does the Human in the Loop feature enable in Agent Studio workflows?', '["Requires human review or approval before an agent takes certain actions", "Enables the setting of only read-only access for users", "Allows agents to write and approve their own changes", "Requires automatic escalation of all tasks assigned to management"]'::jsonb, '[0]'::jsonb, 'Correct.', 'medium'),
  (s2, 'mcq', 'The __________ node enables modular scaling by invoking another worker agent as a sub-process.', '["Switch", "Agent", "Code", "Document Processor"]'::jsonb, '[1]'::jsonb, 'Correct.', 'medium'),
  (s2, 'mcq', 'Which node enables the workflow to retrieve semantic context from uploaded company documents for answering questions?', '["Human Approval Node", "LLM Node", "Loop Node", "RAG Document Tool Node"]'::jsonb, '[3]'::jsonb, 'Correct.', 'medium');

  -- Questions for s3
  INSERT INTO public.questions (subtopic_id, type, question_text, options, correct_answers, explanation, difficulty) VALUES
  (s3, 'mcq', 'Which capability is provided by the Document Tool in AI Agent Studio?', '["Execution of payroll reports", "Dynamic UI form creation tool from a provided document", "Semantic search on uploaded unstructured documents", "Direct manipulation of image files from a provided document"]'::jsonb, '[2]'::jsonb, 'Correct.', 'medium'),
  (s3, 'mcq', 'What step is required after uploading unstructured documents for AI semantic search in the Document Tool?', '["Run the Process Agent Documents scheduled process.", "Enable Permission Groups for the document.", "Process and embed documents into the vector database.", "Share documents on public web."]'::jsonb, '[0]'::jsonb, 'Correct.', 'medium'),
  (s3, 'mcq', 'Which type of tool in Agent Studio allows integration with third-party services via API?', '["Calculator Tool", "User Session Tool", "BI Connector", "External REST Tool"]'::jsonb, '[3]'::jsonb, 'Correct.', 'medium'),
  (s3, 'msq', 'Which three tools are available in AI Agent Studio?', '["User Session Tool", "Deep Link Tool", "Hardware Scaling Tool", "Document Tool"]'::jsonb, '[0, 1, 3]'::jsonb, 'Correct.', 'medium'),
  (s3, 'mcq', 'In Agent Studio, what is a Business Object Tool used for?', '["Resizing user interface forms", "Generating marketing keywords", "Retrieving and transacting on Fusion business objects", "Processing external RSS feeds"]'::jsonb, '[2]'::jsonb, 'Correct.', 'medium');

  -- Questions for s4
  INSERT INTO public.questions (subtopic_id, type, question_text, options, correct_answers, explanation, difficulty) VALUES
  (s4, 'mcq', 'Which is a typical use case for using Topics in prompts?', '["Providing reusable instructions or constraints in agent prompts", "Modifying the agent s user interface in agent prompts", "Configuring additional hardware resources in agent prompts", "Initiating agent upgrades in agent prompts"]'::jsonb, '[0]'::jsonb, 'Correct.', 'medium'),
  (s4, 'mcq', 'What is the role of a Supervisor agent in a multi-agent workflow?', '["To replace all business objects", "To store company documents only", "To monitor server hardware", "To orchestrate and route tasks to worker agents"]'::jsonb, '[3]'::jsonb, 'Correct.', 'medium'),
  (s4, 'mcq', 'What new RAG evaluation metrics are included in agent evaluations in AI Agent Studio?', '["Token usage, latency, and server uptime", "Encryption strength, user authentication, and key rotation", "Prompt length, model temperature, and top-p", "Groundedness (Faithfulness), Answer Relevance, and Context Relevance"]'::jsonb, '[3]'::jsonb, 'Correct.', 'medium'),
  (s4, 'mcq', 'When should evaluations of AI agents be rerun, according to METRO best practices?', '["After an agent''s code is deleted", "Only before initial deployment", "After any changes to the agent or model updates", "Whenever the dashboard displays an error"]'::jsonb, '[2]'::jsonb, 'Correct.', 'medium'),
  (s4, 'mcq', 'In the world described, how are business objects, roles, and workflows incorporated into Oracle Application?', '["They require separate dashboards.", "They are partially integrated using APIs.", "They are natively part of the application.", "They are managed through manual entry."]'::jsonb, '[2]'::jsonb, 'Correct.', 'medium'),
  (s4, 'mcq', 'What is the main purpose of a summarization prompt in Agent Studio?', '["To manage user notifications in AI Agent Studio", "To initiate a file upload in the end user session", "To instruct the AI agent to condense information into a concise output", "To increase the number of fields available"]'::jsonb, '[2]'::jsonb, 'Correct.', 'medium'),
  (s4, 'msq', 'When evaluating agent performance, ________ indicates the time taken by the model to generate responses, which is a key performance metric.', '["Latency", "Correctness", "Token", "Safety"]'::jsonb, '[0, 1]'::jsonb, 'Correct.', 'medium'),
  (s4, 'mcq', 'When configuring security in the Agent Studio post-25C upgrade, what must be enabled before the Security Console can assign custom roles for AI Studio?', '["Permission Groups", "BI Reporting Modules", "Real-Time Auditing", "Backup Scheduling"]'::jsonb, '[0]'::jsonb, 'Correct.', 'medium');

END $$;


-- 2. OCI Data Science Professional
DO $$
DECLARE
  c_id UUID;

  s1 UUID; s2 UUID; s3 UUID; s4 UUID; s5 UUID;
BEGIN
  INSERT INTO public.courses (name, description, icon)
  VALUES ('OCI Data Science Professional', 'Master OCI Data Science lifecycle, notebook sessions, conda environments, AutoML, and MLOps practices.', 'bar-chart')
  RETURNING id INTO c_id;

  INSERT INTO public.subtopics (course_id, name, order_index) VALUES (c_id, 'Introduction and Configuration', 1) RETURNING id INTO s1;
  INSERT INTO public.subtopics (course_id, name, order_index) VALUES (c_id, 'Workspace Design and Setup', 2) RETURNING id INTO s2;
  INSERT INTO public.subtopics (course_id, name, order_index) VALUES (c_id, 'Machine Learning Life Cycle', 3) RETURNING id INTO s3;
  INSERT INTO public.subtopics (course_id, name, order_index) VALUES (c_id, 'MLOps Practices', 4) RETURNING id INTO s4;
  INSERT INTO public.subtopics (course_id, name, order_index) VALUES (c_id, 'Related OCI Services', 5) RETURNING id INTO s5;


  -- Questions for s1
  INSERT INTO public.questions (subtopic_id, type, question_text, options, correct_answers, explanation, difficulty) VALUES
  (s1, 'mcq', 'Which feature of Oracle Cloud Infrastructure Data Science provides an interactive coding environment for building and training machine learning models?', '["Model catalog", "Projects", "Notebook session", "Jobs"]'::jsonb, '[2]'::jsonb, 'OCI Notebook sessions are interactive coding environments for building and training models. A Notebook session is created inside a Data Science project.', 'medium'),
  (s1, 'mcq', 'Which allows the sharing and loading back of ML models into a Notebook session?', '["Model catalog", "Model taxonomy", "Model provenance", "Model deployment"]'::jsonb, '[0]'::jsonb, 'The model catalog is a centralized and managed repository of model artifacts. A stored model includes metadata about the provenance of the model including Git-related information and the script or notebook used to push the model to the catalog. Models stored in the model catalog can be shared across members of a team and they can be loaded back into a Notebook session.', 'medium'),
  (s1, 'mcq', 'What is feature engineering in machine learning used for?', '["To help understand the data set features", "To perform parameter tuning", "To represent the data in a way that helps the model learn more effectively (Correct \u2013 Your", "To interpret ML models"]'::jsonb, '[2]'::jsonb, 'Feature engineering is used to represent the data in a way that helps the model learn more effectively.', 'medium'),
  (s1, 'mcq', 'Which OCI Data Science interaction method can function in both ways — with or without the need of scripting?', '["Language SDKs", "OCI Console", "REST API", "CLI"]'::jsonb, '[1]'::jsonb, 'The OCI Console offers interaction with the Data Science service without the need for scripts.', 'medium'),
  (s1, 'mcq', 'What does the Data Science Service template in Oracle Resource Manager (ORM) NOT automatically create?', '["Dynamic groups", "Policies for a basic use case", "Required user groups", "Individual Data Science users"]'::jsonb, '[3]'::jsonb, 'Oracle Resource Manager (ORM) automatically creates the policies for a basic use case, required user groups, and dynamic groups. It doesn’t create individual Data Science users. Workspace Design and Setup 8 Questions', 'medium');

  -- Questions for s2
  INSERT INTO public.questions (subtopic_id, type, question_text, options, correct_answers, explanation, difficulty) VALUES
  (s2, 'mcq', 'What happens when a notebook session is deactivated?', '["The data on the boot volume is not preserved.", "Compute cost increases due to frequent deactivation.", "The underlying compute instance stops.", "The block volume attached to the Notebook session is permanently deleted."]'::jsonb, '[2]'::jsonb, 'When you deactivate a Notebook session, you save on compute costs because the underlying compute instance stops, and the block volume is detached and preserved.', 'medium'),
  (s2, 'mcq', 'Which is a unique feature of the published Conda environment?', '["It provides availability on Notebook session reactivation.", "It provides a comprehensive environment to solve business use cases.", "It allows you to save the Conda environment in a block volume.", "It allows you to save the Conda environment to an Object Storage bucket."]'::jsonb, '[3]'::jsonb, 'Published Conda environments are customer-created and saved to Object Storage buckets. This is the most unique feature of the published Conda environment.', 'medium'),
  (s2, 'mcq', 'Where are OCI secrets stored?', '["Autonomous Data Warehouse", "OCI Vault", "OCI Object Storage", "Oracle Databases"]'::jsonb, '[1]'::jsonb, 'Secrets are credentials such as passwords or tokens--or any other confidential data that you need to use with other Oracle Cloud Infrastructure services--or perhaps even other external applications or systems. They are stored in OCI Vault.', 'medium'),
  (s2, 'mcq', 'Which CLI command allows a customized Conda environment to be shared with co-workers?', '["odsc conda modify", "odsc conda publish", "odsc conda install", "odsc conda clone"]'::jsonb, '[1]'::jsonb, 'Publishing a Conda environment consists of creating a pack of a Conda environment and uploading it to a specified Object Storage. This allows Conda environments to be shared among colleagues or to persist them across Notebook sessions.', 'medium'),
  (s2, 'mcq', 'Which activity of managing a conda environment requires the conda environment to be activated in your terminal?', '["Installing a Conda environment", "Publishing a Conda environment", "Modifying a Conda environment", "Cloning a Conda environment"]'::jsonb, '[2]'::jsonb, 'To modify the libraries in the Conda environment, it must remain active.', 'medium'),
  (s2, 'mcq', 'What is a conda environment?', '["An open source package and environment management system", "An environment deployment system on Oracle AI", "A collection of kernels", "A system that manages package independencies"]'::jsonb, '[0]'::jsonb, 'Conda is an open source package management system and environment management system. Conda as a package manager helps you find and install packages.', 'medium'),
  (s2, 'mcq', 'Which model has an open source, open model format that allows you to run machine learning models on different platforms?', '["TensorFlow", "ONNX", "PyTorch", "PySpark"]'::jsonb, '[1]'::jsonb, 'ONNX is an open source, open model package that allows you to save a model from different machine learning (ML) libraries into a single, portable format that is independent of the training library. TensorFlow and PyTorch are open source ML frameworks for deep neural networks. PySpark is a framework used for processing a huge amount of data. Machine Learning Life Cycle 6 Questions', 'medium');

  -- Questions for s3
  INSERT INTO public.questions (subtopic_id, type, question_text, options, correct_answers, explanation, difficulty) VALUES
  (s3, 'mcq', 'Which function represents the difference between the predictive value and the target value?', '["Fit function", "Update function", "Cost function", "Optimizer function"]'::jsonb, '[2]'::jsonb, 'The objective of the loss function is to represent the difference between the predicted values Ŷ and the true targets Y as a single number, the loss score. The loss function is also known as the cost function.', 'medium'),
  (s3, 'mcq', 'Which stage in the machine learning life cycle helps identify imbalances present in data?', '["Data Modeling", "Data Exploration", "Data Monitoring", "Data Access"]'::jsonb, '[1]'::jsonb, 'The process of building and breaking the ML model has six steps. Of these, Data Exploration is used to cleanse the data by identifying corrupt, inaccurate, and incomplete data and replacing or deleting it. This also helps in identifying the imbalances present in the data.', 'medium'),
  (s3, 'mcq', 'You are working for a bank. You are required to analyze customer accounts'' access data and flag any irregular access attempts. Which OCI Data Science operator are you most likely to use?', '["Forecasting", "PII", "Anomaly"]'::jsonb, '[2]'::jsonb, 'Anomaly detection is used for finding anomalies or any irregularities in your data.', 'medium'),
  (s3, 'mcq', 'Which step is a part of AutoML pipeline?', '["Feature Extraction", "Model Saved to Model Catalog", "Feature Selection", "Model Deployment"]'::jsonb, '[2]'::jsonb, 'Oracle AutoML automates four major steps in the machine learning modeling process to deliver significant productivity improvements for data scientists. They are Algorithm Selection, Adaptive Sampling, Feature Selection, and Model Tuning.', 'medium'),
  (s3, 'mcq', 'What do you use the score.py file for?', '["Defining the scaling strategy", "Defining the required Conda environments", "Executing the inference logic code", "Configuring the deployment infrastructure"]'::jsonb, '[2]'::jsonb, 'This file contains the function definitions that are necessary to load your model to memory and make predictions. The two functions are called load_model() and predict(). The function parameters are not customizable. For example, you can define data transformations in predict() before calling the inference method of your estimator object. In other words, it is used for executing the inference logic code.', 'medium'),
  (s3, 'mcq', 'Which activity is NOT a part of the machine learning life cycle?', '["Database Management", "Model Deployment", "Modeling", "Data Access"]'::jsonb, '[0]'::jsonb, 'The machine learning life cycle has six important tasks: Data Access, Data Exploration and Data Preparation, Modeling, Validation, Model Deployment, and Monitoring/Refresh/Retirement. Database Management is not a part of this life cycle. MLOps Practices 8 Questions', 'medium');

  -- Questions for s4
  INSERT INTO public.questions (subtopic_id, type, question_text, options, correct_answers, explanation, difficulty) VALUES
  (s4, 'mcq', 'Which statement us true about machine learning models?', '["A high-quality model will not need to be retrained as new information is received.", "Static predictions become increasingly accurate over time.", "Model performance degrades over time due to changes in data.", "Data models are more static and generally require fewer updates than software code."]'::jsonb, '[2]'::jsonb, 'Machine learning models are data driven. Whenever the data changes, the model needs retraining. Else the performance degrades over time.', 'medium'),
  (s4, 'mcq', 'Which step is unique to MLOps, as opposed to DevOps?', '["Continuous Training", "Continuous Integration", "Continuous Deployment", "Continuous Delivery"]'::jsonb, '[0]'::jsonb, 'Continuous Training is unique to MLOps and refers to the automatic retraining of ML models for redeployment.', 'medium'),
  (s4, 'mcq', 'In the OCI Console, as part of Monitoring, of what is triggering a Pager Duty notification an example?', '["Event", "Action", "Rule", "Function"]'::jsonb, '[1]'::jsonb, 'Action is a user-defined response to an event, such as triggering a notification. Triggering a Pager Duty notification in this case is an example of Action.', 'medium'),
  (s4, 'mcq', 'Which statement is true about logs for Oracle Cloud Infrastructure Jobs?', '["Integrating Data Science Jobs resources with Logging is mandatory.", "Logs are automatically deleted when the job and job run are deleted.", "All stdout and stderr are automatically stored when automatic log creation is enabled. (Correct", "Each job run sends outputs to a single log for that job."]'::jsonb, '[2]'::jsonb, 'When working with custom logs, the customer captures log events collected in a particular context. Here the standard output (stdout) and standard error (stderr) outputs from job artifacts are automatically captured.', 'medium'),
  (s4, 'mcq', 'As a data scientist, you require a pipeline to train ML models. When can a pipeline run be initiated?', '["After the Active state", "After it is created", "During the pipeline run state", "Before the Active state"]'::jsonb, '[0]'::jsonb, 'A pipeline life cycle has four states: Create, Active, Run, and Delete. The pipeline run state gets initiated after the active state.', 'medium'),
  (s4, 'mcq', 'Why would you use a mini batch when processing a job in Data Science Jobs?', '["You do not need to process data quickly.", "You want several distributed models to run simultaneously.", "You want to process data frequently.", "There is a small amount of total data to process."]'::jsonb, '[2]'::jsonb, 'Sometimes so much data comes in or needs to be processed so quickly that a mini batch is preferable. This is a set of more frequent job runs that processes a smaller amount of data at a time. A good example of when to use a mini batch is a bank analyzing transactions to search for fraud. Every several minutes, a job is run that takes data from Object Storage and looks for fraudulent transactions.', 'medium'),
  (s4, 'mcq', 'Which statement is true about Oracle Cloud Infrastructure Data Science Jobs?', '["Jobs provisions the infrastructure to run a process on demand.", "Jobs comes with a set of standard tasks that cannot be customized.", "You must use a single Shell/Bash or Python artifact to run a job.", "You must create and manage your own Jobs infrastructure."]'::jsonb, '[0]'::jsonb, 'A job is a template that describes the task. In each job run, you can override some of the job configuration, and most importantly, the environment variables and CLI arguments. You can have the same job with several sequentially or simultaneously started job runs with different parameters.', 'medium');

  -- Questions for s5
  INSERT INTO public.questions (subtopic_id, type, question_text, options, correct_answers, explanation, difficulty) VALUES
  (s5, 'mcq', 'What is the name of the machine learning library used in Apache Spark?', '["GraphX", "Structured Streaming", "MLlib", "HadoopML"]'::jsonb, '[2]'::jsonb, 'PySpark 3.2 and the Big Data service leverage the power of Apache Spark and MLlib to speed up model building.', 'medium'),
  (s5, 'mcq', 'Which option indicates the three types of data used for Data Labeling?', '["Image, text, document", "Image, audio, document", "Graphic, text, document", "Text, audio, video"]'::jsonb, '[0]'::jsonb, 'Data Labeling is the process of identifying properties (labels) of documents, text, and images (records), and annotating (labeling) them with those properties.', 'medium'),
  (s5, 'mcq', 'You are a researcher who requires access to large data sets. Which OCI service would you use?', '["ADW", "OCI Data Science", "Oracle Databases", "Oracle Open Data"]'::jsonb, '[3]'::jsonb, 'Oracle Open Data is a service from Oracle for Research that makes large data sets available to researchers around the world. It curates information like spatial images, protein sequences, and annotated text files from the world’s leading scientific data sources.', 'medium'),
  (s5, 'mcq', 'Which OCI service provides a scalable environment for developers and data scientists to run Apache Spark applications at scale?', '["Data Flow", "Anomaly Detection", "Data Science", "Data Labeling"]'::jsonb, '[0]'::jsonb, 'Oracle Cloud Infrastructure Data Flow is a fully managed service for running Apache Spark applications. It allows developers to focus on their applications and provides an easy runtime environment to execute them. It has a simple user interface with API support for integration with applications and workflows.', 'medium');

END $$;


-- 3. Oracle AI Vector Search & Database 23ai
DO $$
DECLARE
  c_id UUID;

  sv1 UUID; sv2 UUID; sv3 UUID; sv4 UUID; sv5 UUID; sv6 UUID; sv7 UUID; sv8 UUID; sv9 UUID; sv10 UUID;
BEGIN
  INSERT INTO public.courses (name, description, icon)
  VALUES ('Oracle AI Vector Search & Database 23ai', 'Master AI Vector Search, distance metrics (Euclidean, Cosine, Dot product), Vector Indexes, DDL/DML, and SGA Vector Pool.', 'layers')
  RETURNING id INTO c_id;

  INSERT INTO public.subtopics (course_id, name, order_index) VALUES (c_id, 'Test other Vector Functions', 1) RETURNING id INTO sv1;
  INSERT INTO public.subtopics (course_id, name, order_index) VALUES (c_id, 'Test other Distance Functions', 2) RETURNING id INTO sv2;
  INSERT INTO public.subtopics (course_id, name, order_index) VALUES (c_id, 'Narrow Search Results', 3) RETURNING id INTO sv3;
  INSERT INTO public.subtopics (course_id, name, order_index) VALUES (c_id, 'Find Closest Vector', 4) RETURNING id INTO sv4;
  INSERT INTO public.subtopics (course_id, name, order_index) VALUES (c_id, 'Creating and Finding Nearest Vector', 5) RETURNING id INTO sv5;
  INSERT INTO public.subtopics (course_id, name, order_index) VALUES (c_id, 'DDL Operations on Vectors', 6) RETURNING id INTO sv6;
  INSERT INTO public.subtopics (course_id, name, order_index) VALUES (c_id, 'DML Operations on Vectors', 7) RETURNING id INTO sv7;
  INSERT INTO public.subtopics (course_id, name, order_index) VALUES (c_id, 'Vector Indexes and Memory', 8) RETURNING id INTO sv8;
  INSERT INTO public.subtopics (course_id, name, order_index) VALUES (c_id, 'Running Basic Queries on Vectors', 9) RETURNING id INTO sv9;
  INSERT INTO public.subtopics (course_id, name, order_index) VALUES (c_id, 'Oracle AI Vector Search Workflow', 10) RETURNING id INTO sv10;


  -- Questions for sv1
  INSERT INTO public.questions (subtopic_id, type, question_text, options, correct_answers, explanation, difficulty) VALUES
  (sv1, 'mcq', 'What is the primary purpose of the VECTOR_SERIALIZE() function in Oracle Database 23ai, as presented in the sources?', '["To determine the number of dimensions in a vector.", "To create a new vector from a string representation.", "To calculate the distance between two vectors.", "To convert a vector to a string or CLOB data type."]'::jsonb, '[3]'::jsonb, 'vector to a string or CLOB data type. The function can optionally specify the target data type using the returning clause, such as returning varchar2(1000) or returning CLOB. This function is distinct from to_vector(), which converts a string representation to a vector.', 'medium'),
  (sv1, 'mcq', 'Which of the following SQL statements demonstrates the correct usage of the to_vector() function in Oracle Database 23ai?', '["SELECT to_vector(34.6, 77.8, 2, float32) FROM dual", "SELECT to_vector(''[34.6, 77.8]'', 2, float32) FROM dual", "SELECT to_vector([34.6, 77.8], 2, float32) FROM dual", "SELECT to_vector(''34.6, 77.8'', 2, float32) FROM dual"]'::jsonb, '[1]'::jsonb, 'string representation of the vector enclosed in square brackets. The format is to_vector(''[value1, value2, ...]'', dimension_count, data_type). Options a), c), and d) use incorrect syntax. Option a) provides individual values instead of a string representation. Option c) lacks the square brackets. Option d) uses an array-like notation which is not supported for vector creation in the sources.', 'medium'),
  (sv1, 'mcq', 'Which SQL statement correctly retrieves the format of the numbers stored in the vector ''''[34.6, 77.8, 9, 10]''1'' using the vector_dimension_format () function in Oracle Database 23ai?', '["SELECT vector_dimension_format ( 34.6, 77.8, 9, 10, 3 ''1'') FROM dual", "SELECT vector_dimension_format (''INT8'') FROM dual;", "SELECT vector_dimension_format(vector(\u2018[34.6, 77.8, 9, 10]\u2019,4, INT8)) FROM dual; (Correct \u2013", "SELECT vector_dimension_format (34.6, 77.8, 9, 10) FROM dual"]'::jsonb, '[2]'::jsonb, 'vector_dimension_format (vector(''[34.6, 77.8, 9, 10]'', 4, INT8)). The other options are incorrect because:Option a) passes a string literal directly to the function, not a vector object.Option c) attempts to pass individual numeric values, not a vector.Option d) provides a string literal ''INT8'', which is not the correct way to determine the vector''s format. The format is determined by the data type used when creating the vector, not by a separate string input.', 'medium'),
  (sv1, 'mcq', 'What is the primary purpose of the VECTOR_NORM() function in Oracle Database 23ai?', '["To determine the number of dimensions in a vector.", "To return the magnitude or length of a vector.", "To calculate the Euclidean distance between two vectors.", "To convert a vector to a string representation."]'::jsonb, '[1]'::jsonb, '"distance from the origin to the vector," which is synonymous with the vector''s magnitude or length. This function is distinct from distance functions like VECTOR_DISTANCE() or shorthand operators like , which calculate the distance between two vectors.', 'medium'),
  (sv1, 'mcq', 'Which of the following actions will result in an error when using VECTOR_DIMENSION_COUNT() in Oracle Database 23ai?', '["Providing a vector with duplicate values for its components.", "Using a vector with a data type that is not supported by the function.", "Providing a vector with a dimensionality that exceeds the specified dimension count. (Correct \u2013", "Calling the function on a vector that has been created with to_vector()."]'::jsonb, '[2]'::jsonb, 'throw an error (ORA-51803) if the vector''s actual dimension count does not match the dimension count specified in the function call. This error is not triggered by other factors like data type, duplicate values, or the vector''s creation method. Test other Distance Functions 5 Questions', 'medium');

  -- Questions for sv2
  INSERT INTO public.questions (subtopic_id, type, question_text, options, correct_answers, explanation, difficulty) VALUES
  (sv2, 'mcq', 'Which vector distance function is equivalent to using the shorthand syntax v1  v2 in Oracle Database 23ai?', '["L2_DISTANCE (v1, v2)", "COSINE_DISTANCE (v1, v2)", "INNER_PRODUCT (v1, v2)", "L1_DISTANCE (v1, v2)"]'::jsonb, '[0]'::jsonb, 'Euclidean distance between vectors. The L2_DISTANCE() function is also defined as calculating the Euclidean distance.', 'medium'),
  (sv2, 'mcq', 'If the VECTOR_DISTANCE() function is used with the HAMMING metric, what characteristic of the vectors is being compared?', '["The number of components that have different values.", "The product of the corresponding components.", "The angle between the vectors.", "The sum of the absolute differences between corresponding components."]'::jsonb, '[0]'::jsonb, 'dissimilarity between two strings of equal length. It counts the number of positions at which the corresponding symbols are different.', 'medium'),
  (sv2, 'mcq', 'What is the main advantage of using the shorthand syntax like  or  for vector distance calculations?', '["It allows for more complex mathematical operations within the distance calculation.", "It improves the readability and conciseness of the SQL queries.", "It reduces the computational overhead of vector comparisons.", "It enables the use of custom-defined distance functions."]'::jsonb, '[1]'::jsonb, 'alternative to the more verbose VECTOR_DISTANCE() function. Using operators like  or  can make the queries more compact and easier to understand, especially when performing multiple vector comparisons.', 'medium'),
  (sv2, 'mcq', 'Which of the following shorthand notations in Oracle Database 23ai represents the cosine similarity between two vectors, v1 and v2?', '["v1  v2", "v1  v2", "v1  v2", "v1  v2"]'::jsonb, '[3]'::jsonb, 'equivalent to the cosine similarity distance function. The other options represent different distance metrics:   corresponds to Euclidean distance.  represents the negative dot product.4  is not a valid shorthand notation for vector distances in the sources.', 'medium');

  -- Questions for sv3
  INSERT INTO public.questions (subtopic_id, type, question_text, options, correct_answers, explanation, difficulty) VALUES
  (sv3, 'mcq', 'In the following SQL query, which distance function should replace the FUNCTION keyword to find the closest vectors?SQL> SELECT id, vsize, shape, color, to_number(Function(vector(''[16, 3]''), v, EUCLIDEAN)) distance FROM vt2 WHERE id > 30 AND id  ORDER BY vector_distance(vector(''[16, 3]''), v, EUCLIDEAN) FETCH FIRST 3 ROWS ONLY;', '["cosine_distance", "L1_distance", "inner_product", "vector_distance"]'::jsonb, '[3]'::jsonb, 'between two vectors using a specific metric (like Euclidean distance). It is the most appropriate choice for finding the closest vectors. cosine_distance measures the cosine of the angle between two vectors, which is useful for understanding the orientation of the vectors rather than their absolute distances. It is not suitable for finding the "closest" vectors in terms of Euclidean distance. inner_product computes the dot product of two vectors. While it can provide some insights into the similarity of the vectors, it does not directly measure distance. L1_distance, also known as Manhattan distance, sums the absolute differences of their coordinates. While it''s another way to measure distance, the query specifies using Euclidean distance, making this option less suitable in this context.', 'medium'),
  (sv3, 'mcq', 'What data types can be used for the components of a VECTOR column in Oracle Database 23ai?', '["VARCHAR2 only", "Both NUMBER and FLOAT", "NUMBER only", "FLOAT only"]'::jsonb, '[1]'::jsonb, 'both NUMBER and FLOAT data types for the vector elements. E.g., VECTOR('''', 2, FLOAT32) uses a FLOAT data type. Implicitly, when no data type is specified, the examples suggest that NUMBER is the assumed data type.', 'medium'),
  (sv3, 'mcq', 'What is the primary purpose of using the VECTOR_DISTANCE() function in a SQL query?', '["To group data points based on their color attributes.", "To sort the results in ascending order of their IDs.", "To determine the geometric shape of the data points.", "To calculate the distance between vectors for similarity comparison."]'::jsonb, '[3]'::jsonb, 'used to compute the distance between vectors, which serves as a measure of similarity. This distance calculation is crucial for finding the closest vectors to the target vector.', 'medium'),
  (sv3, 'mcq', 'Assuming we have a table called VT2 that contains vectors for mapping various shapes, colors, and sizes, what is the primary purpose of the following UPDATE statements? SQL&gt; UPDATE vt2SET shape = ''Triangle''WHERE id IN (2, 4, 7, 22, 31, 41, 44, 55);&nbsp;SQL&gt; UPDATE vt2SET size = ''Medium''WHERE id IN (5, 22, 25, 32, 34, 42, 43, 53, 54, 55);', '["To modify the vector values stored in the VT2 table.", "To add new rows of data to the VT2 table with different sizes and shapes.", "To delete rows from the VT2 table that do not meet specific criteria.", "To assign attributes like size and shape to existing vectors based on their IDs. (Correct \u2013 Your"]'::jsonb, '[3]'::jsonb, 'populate the SIZE and SHAPE columns of the VT2 table. These columns are added to the table to store attributes associated with each vector. The UPDATE statements use WHERE clauses to selectively modify rows based on their ID, linking specific attributes to corresponding vectors.', 'medium'),
  (sv3, 'mcq', 'What is Exact Similarity Search also called?', '["Vector search", "Efficient search", "Flat search", "Approximate search"]'::jsonb, '[2]'::jsonb, 'to as Flat Search. Find Closest Vector 5 Questions', 'medium');

  -- Questions for sv4
  INSERT INTO public.questions (subtopic_id, type, question_text, options, correct_answers, explanation, difficulty) VALUES
  (sv4, 'mcq', 'What is a potential drawback of Exact Similarity Search?', '["Significant search times", "Limited accuracy", "Inaccurate results", "Use of vector indexes"]'::jsonb, '[0]'::jsonb, 'perfect search quality and the most accurate results, it can potentially result in significant search times.', 'medium'),
  (sv4, 'mcq', 'What concept can be applied to vectorized data that is not uniformly distributed?', '["Dimensionality reduction", "Indexing", "Normalization", "Clustering"]'::jsonb, '[3]'::jsonb, 'representing groups of similar data. These clusters arise because the data is not evenly spread out (uniformly distributed).', 'medium'),
  (sv4, 'mcq', 'Multi-Vector Similarity Search is typically used for:', '["Multi-document search", "Image recognition", "Single-vector comparisons", "Exact vector matching"]'::jsonb, '[0]'::jsonb, 'primarily employed for searches involving multiple documents. In this approach, documents are divided into chunks, and each chunk is embedded into individual vectors for comparison and retrieval.', 'medium'),
  (sv4, 'mcq', 'Based on the sources, which of these is a valid way to construct a vector with the values (10, 20) using the VECTOR() constructor?', '["VECTOR ( [10, 20] )", "VECTOR ( ''[10, 20]'' )&nbsp;", "VECTOR [''10, 20'']", "VECTOR (10, 20)"]'::jsonb, '[1]'::jsonb, 'to create vectors. Square brackets and commas are used within the string to delimit the vector values. The other options do not follow the syntax required to create vectors.', 'medium'),
  (sv4, 'mcq', 'Which of the following is NOT a characteristic of Approximate Similarity Search?', '["Always provides exact matches", "Can be more efficient", "Uses vector indexes", "Uses target accuracy"]'::jsonb, '[0]'::jsonb, 'leverages vector indexes to enhance efficiency but may not always produce exact matches. It aims for a target accuracy level rather than perfect precision. Creating and Finding Nearest Vector 5 Questions', 'medium');

  -- Questions for sv5
  INSERT INTO public.questions (subtopic_id, type, question_text, options, correct_answers, explanation, difficulty) VALUES
  (sv5, 'mcq', 'You need to find the Euclidean distance between the vectors (0, 0) and (3, 4). Which SQL statement will produce the correct result?', '["SELECT VECTOR_DISTANCE (VECTOR(''[0,0]''), VECTOR(''[3,4]''), EUCLIDEAN)", "SELECT VECTOR_DISTANCE ((0, 0), (3, 4))", "SELECT EUCLIDEAN_DISTANCE (VECTOR(''[0,0]''), VECTOR(''[3,4]''))", "SELECT VECTOR_DISTANCE ('''', (3, 4))"]'::jsonb, '[0]'::jsonb, 'arguments: The first vector, created using the VECTOR() constructor.The second vector, also created using the VECTOR() constructor.The distance metric to use, which is EUCLIDEAN in this case.', 'medium'),
  (sv5, 'mcq', 'Which of the following SQL statements correctly creates a two-dimensional vector with the coordinates (4, -3) using the VECTOR() constructor?', '["SELECT VECTOR(''(4, -3)'')", "SELECT VECTOR(4 -3)", "SELECT VECTOR(4, -3)", "SELECT VECTOR(''[4, -3]'')"]'::jsonb, '[3]'::jsonb, 'square brackets [] and passed as a single string argument to the VECTOR() constructor.', 'medium'),
  (sv5, 'mcq', 'What is the primary purpose of the vector_distance() function in Oracle Database 23ai?', '["To enable similarity searches by measuring the distance between vectors", "To calculate the dot product of two vectors.", "To find the magnitude (length) of a single vector.", "To determine the angle between two vectors."]'::jsonb, '[0]'::jsonb, 'search by returning the distance between two vectors.', 'medium'),
  (sv5, 'mcq', 'When adding a VECTOR column in a table, what additional information can you specify besides the column name?', '["The number of dimensions and the data type of the vector elements.", "The compression algorithm.", "The storage size in bytes.", "The default value for the column."]'::jsonb, '[0]'::jsonb, 'can specify the number of dimensions and the data type of the vector elements. DDL Operations on Vectors 5 Questions', 'medium');

  -- Questions for sv6
  INSERT INTO public.questions (subtopic_id, type, question_text, options, correct_answers, explanation, difficulty) VALUES
  (sv6, 'mcq', 'What is the maximum number of dimensions a VECTOR data type can have in Oracle Database 23ai?', '["1,536", "65,536", "1,024", "4,096"]'::jsonb, '[1]'::jsonb, 'strictly greater than zero with a maximum of 65535 for non-BINARY vectors and 65528 for BINARY vectors.', 'medium'),
  (sv6, 'mcq', 'Can you create a table with multiple VECTOR columns?', '["Yes, a table can have multiple VECTOR columns.", "No, VECTOR columns can only be added to existing tables.", "No, a table can only have one VECTOR column.", "Yes, but only if all VECTOR columns have the same dimensions."]'::jsonb, '[0]'::jsonb, 'VECTOR columns, each potentially having different dimensions and data types.', 'medium'),
  (sv6, 'mcq', 'Which SQL statement correctly adds a VECTOR column named v with 3 dimensions and FLOAT32 format to an existing table named my_table?', '["ALTER TABLE my_table ADD v VECTOR(3, FLOAT32)", "ALTER TABLE my_table ADD (v VECTOR(3, FLOAT32))", "ALTER TABLE my_table MODIFY (v VECTOR(3, FLOAT32))", "UPDATE my_table SET v = VECTOR(3, FLOAT32)"]'::jsonb, '[0]'::jsonb, 'VECTOR column to an existing table.', 'medium');

  -- Questions for sv7
  INSERT INTO public.questions (subtopic_id, type, question_text, options, correct_answers, explanation, difficulty) VALUES
  (sv7, 'mcq', 'What happens when you attempt to insert a vector with an incorrect number of elements into a VECTOR column with a defined number of dimensions?', '["The database ignores the defined dimensions and inserts the vector as is.", "The database pads the vector with zeros to match the defined dimensions.", "The insert operation fails, and an error message is thrown.", "The database truncates the vector to fit the defined dimensions."]'::jsonb, '[2]'::jsonb, 'wrong number of elements or an incorrect format into a column with defined dimensions result in an error.', 'medium'),
  (sv7, 'mcq', 'Which of the following SQL statements will successfully insert a vector into a table named vectors with a single VECTOR column named v?', '["INSERT INTO vectors VALUES (''{1.1, 2.2, 3.3}'')", "INSERT INTO vectors VALUES ((1.1, 2.2, 3.3))", "INSERT INTO vectors (v) VALUES (''[1.1, 2.2, 3.3]'')", "INSERT INTO vectors (v) VALUES (1.1, 2.2, 3.3)"]'::jsonb, '[2]'::jsonb, 'syntax for inserting vectors:  Numbers should be separated by commas. The array of numbers must be enclosed in single quotes.', 'medium'),
  (sv7, 'mcq', 'When defining a VECTOR column, what does specifying the number of dimensions achieve?', '["It specifies the type of data that can be stored in the vector (e.g., text, image).", "It determines the precision of the numeric values stored in the vector.", "It improves the performance of similarity searches.", "It enforces the number of elements allowed in the vector."]'::jsonb, '[3]'::jsonb, 'constraint, effectively limiting the number of elements within a vector.', 'medium'),
  (sv7, 'mcq', 'Examine the following SQL statement:CREATE TABLE my_vectors (id NUMBER, embedding VECTOR) ;What is the default number format for the "embedding" column?', '["FLOAT32", "FLOAT64", "INT8", "BINARY_DOUBLE"]'::jsonb, '[0]'::jsonb, 'vector formats, the default for a VECTOR without a specified format is FLOAT32.', 'medium'),
  (sv7, 'mcq', 'How can vector data be manipulated within an Oracle Database using Data Manipulation Language (DML)?', '["Insertion, updates, deletion, and loading", "Insertion and updates", "Insertion only", "Insertion, updates, and deletion"]'::jsonb, '[0]'::jsonb, 'operations on vectors in Oracle Database:Inserting vectors directly into a table using INSERT INTO statements.Updating existing vectors within a table using UPDATE statements.Deleting vectors from a table using DELETE FROM statements.Loading data from external files (like a .csv file) into tables using SQL*Loader. Vector Indexes and Memory 5 Questions', 'medium');

  -- Questions for sv8
  INSERT INTO public.questions (subtopic_id, type, question_text, options, correct_answers, explanation, difficulty) VALUES
  (sv8, 'mcq', 'What is the significance of the VECTOR_MEMORY_SIZE parameter in Oracle Database 23ai?', '["It defines the maximum memory usage allowed for the Vector Pool in the SGA.", "It limits the maximum number of vectors that can be stored in the Vector Pool.", "It determines the dimensionality of vectors that can be created.", "It sets the precision of floating-point numbers used in vector computations."]'::jsonb, '[0]'::jsonb, 'used to control the size of the Vector Pool. The parameter can be set at both the database (CDB) and pluggable database (PDB) levels. The value set for this parameter dictates the maximum amount of SGA memory that can be allocated to the Vector Pool, effectively limiting its size.4', 'medium'),
  (sv8, 'mcq', 'What is the primary function of a Vector Index in Oracle Database 23ai?', '["To store vector data directly on disk.", "To calculate the dot product of two vectors.", "To efficiently search for vectors that are similar to a given query vector.", "To convert traditional relational data into vector representations."]'::jsonb, '[2]'::jsonb, 'data structures designed to optimize vector search operations. These indexes employ techniques like clustering, partitioning, and neighbor graphs to significantly reduce the search space, enabling fast and efficient retrieval of similar vectors.', 'medium'),
  (sv8, 'mcq', 'Where is the Vector Pool located within the Oracle Database 23ai architecture?', '["In the Database Buffer Cache.", "In the Redo Log Buffer.", "In the System Global Area (SGA).", "In the Program Global Area (PGA)."]'::jsonb, '[2]'::jsonb, 'System Global Area (SGA). The SGA is a shared memory region that holds data and control information for an Oracle Database instance.', 'medium'),
  (sv8, 'mcq', 'What is the approximate memory requirement (in GB) for an In-memory Neighbor Graph index with 1,000,000 rows, each represented by a vector with 1024 dimensions and a vector format size of 4 bytes?', '["About 3.7 GB", "About 7.4 GB", "About 5.0 GB", "About 1.9 GB"]'::jsonb, '[2]'::jsonb, 'of rows. Applying the values from the question: 1.3 * 4 * 1024 * 1,000,000 = 5,324,800,000 bytes, which is approximately 5.0. The constant 1.3 accounts for overhead and graph layers.', 'medium'),
  (sv8, 'mcq', 'Which of the following is a recommended approach when there is insufficient RAM to accommodate large vector indexes?', '["Utilize Inverted File Flat (IVF) indexes.", "Reduce the dimensionality of the vectors.", "Increase the size of the Redo Log Buffer.", "Disable the Vector Pool in the SGA."]'::jsonb, '[0]'::jsonb, 'Flat (IVF) indexes as an alternative when available RAM is insufficient to handle large vector indexes. IVF indexes leverage both the buffer cache and disk storage, making them more suitable for scenarios with RAM constraints. Running Basic Queries on Vectors 5 Questions', 'medium');

  -- Questions for sv9
  INSERT INTO public.questions (subtopic_id, type, question_text, options, correct_answers, explanation, difficulty) VALUES
  (sv9, 'mcq', 'Considering the limitations of comparison operations between vectors, which approach would be suitable for finding vectors similar to a query vector q in a table named items with a vector column named embedding?', '["SELECT * FROM items WHERE embedding < q", "Use specialized functions or libraries that calculate vector distances or similarities. (Correct", "Convert the vectors to string representations and compare them using string matching functions.", "SELECT * FROM items WHERE embedding = q"]'::jsonb, '[1]'::jsonb, 'vectors using operators like = or < are not supported and result in errors (ORA-22848). Therefore, options a) and b) are incorrect as they attempt to directly compare vectors using unsupported operators. Option d), while potentially feasible, is not recommended because string representations of vectors might not accurately reflect their underlying geometric or semantic relationships. The correct approach, as suggested by option c), involves utilizing specialized functions or libraries designed for vector similarity calculations. These functions often employ techniques like cosine similarity, Euclidean distance, or other distance metrics that are appropriate for measuring vector relationships.', 'medium'),
  (sv9, 'mcq', 'Which of the following SQL statements correctly inserts a vector into a table named product_embeddings with a column named embedding of the VECTOR data type?', '["INSERT INTO product_embeddings VALUES ( ''[0.1, 0.2, 0.3]'')", "INSERT INTO product_embeddings VALUES ( (0.1, 0.2, 0.3))", "INSERT INTO product_embeddings VALUES ( \"[0.1, 0.2, 0.3]\")", "INSERT INTO product_embeddings VALUES ( VECTOR (0.1, 0.2, 0.3))"]'::jsonb, '[0]'::jsonb, '"INSERT INTO product_embeddings VALUES ( ''[0.1, 0.2, 0.3]'')" is the correct way to insert a vector.  You need to separate each number with a comma. You need to enclose the array with single quotes.  The other options use incorrect syntax for vector creation or insertion.', 'medium'),
  (sv9, 'mcq', 'Which of the following mathematical operations can be directly performed between two vectors (v1 and v2) using built-in functions or operators in Oracle Database 23ai?', '["Addition (v1 + v2)", "Subtraction (v1 - v2)", "Multiplication (v1 - v2)", "None of these"]'::jsonb, '[3]'::jsonb, 'performing arithmetic operations like addition, subtraction, multiplication, or division between vectors using built-in functions or operators is not supported.', 'medium'),
  (sv9, 'mcq', 'What does the error message "ORA-22848: cannot use VECTOR type as comparison key" indicate?', '["The VECTOR data type is not supported for indexing purposes.", "The query is trying to insert a vector with incorrect formatting.", "The dimensionality of the vectors being compared is incompatible.", "An attempt was made to compare two vectors using operators like = or <."]'::jsonb, '[3]'::jsonb, 'using standard comparison operators result in this error. This highlights a key concept: vectors, unlike scalar values, cannot be directly compared using the usual relational operators in Oracle Database. Specialized functions or techniques are required for comparing vectors, such as calculating distances or similarities.', 'medium'),
  (sv9, 'mcq', 'What type of data, can be used for creating Vector Embeddings?', '["Image data", "Audio data", "Text data", "All of the above"]'::jsonb, '[3]'::jsonb, 'representation of text, image, audio, or video data that encodes the semantic content of the data. Oracle AI Vector Search Workflow 5 Questions', 'medium');

  -- Questions for sv10
  INSERT INTO public.questions (subtopic_id, type, question_text, options, correct_answers, explanation, difficulty) VALUES
  (sv10, 'mcq', 'What is the first step in the Oracle AI Vector Search Workflow?', '["Query Data with Similarity Searches", "Generate Vector Embeddings", "Vector Indexes", "Store Vector Embeddings"]'::jsonb, '[1]'::jsonb, 'Search workflow is to "Generate Vector Embeddings." Vector embeddings are mathematical representations of data points (like text, images, or other unstructured content) in a multi-dimensional vector space. Generating these embeddings is the foundation for enabling similarity searches within the Oracle Database environment.', 'medium'),
  (sv10, 'mcq', 'What types of searches can be combined when querying data in Oracle Database 23ai that includes vector embeddings?', '["Geospatial searches and time-series analysis.", "Keyword searches and sentiment analysis.", "Similarity searches and relational searches.", "Image recognition searches and natural language processing."]'::jsonb, '[2]'::jsonb, 'combination of "Similarity searches" and "Relational searches." This powerful capability enables users to perform complex queries that leverage both the semantic relationships captured in vector embeddings (similarity searches) and the structured information stored in relational tables (relational searches). This combined approach offers greater flexibility and precision in retrieving relevant data.', 'medium'),
  (sv10, 'mcq', 'What is the main advantage of creating Vector Indexes in Oracle Database 23ai?', '["They compress the vector data, reducing storage space.", "They allow for direct comparison of vectors using operators like = or <.", "They convert relational data into vector representations.", "They enable efficient searching for similar vectors in large vector spaces."]'::jsonb, '[3]'::jsonb, 'similar vectors in large vector spaces.Explanation: Vector Indexes can optimize vector search operations. These indexes are specifically designed to handle the challenges of searching for similar vectors within potentially vast vector spaces. They employ various techniques to speed up the search process, making it feasible to find relevant vectors efficiently even when dealing with massive amounts of data.', 'medium'),
  (sv10, 'mcq', 'Where can vector embeddings be generated in Oracle Database 23ai?', '["Only within the database", "Both outside and within the database", "Nowhere, vector embeddings are not generated", "Only outside the database"]'::jsonb, '[1]'::jsonb, '"Outside the DB" and "Within the DB." Oracle Database 23ai offers flexibility in terms of where these embeddings can be created. Users can choose to generate embeddings using external tools or services and then import them into the database. Alternatively, they can leverage the capabilities of Oracle Database 23ai itself to generate embeddings directly within the database environment.', 'medium'),
  (sv10, 'mcq', 'How are vector embeddings stored in Oracle Database 23ai?', '["By creating columns with the VECTOR data type in relational tables.", "They are stored in a separate, specialized vector database.", "They are appended as metadata to existing data files.", "They are not stored; they are only used for querying."]'::jsonb, '[0]'::jsonb, 'columns with the data type VECTOR within the relational tables of the database. This approach integrates vector data seamlessly into the existing relational database structure, allowing for efficient management and querying alongside other business data.', 'medium');

END $$;


-- 4. Oracle Fusion Cloud Applications PaaS Practice (50 MCQs)
DO $$
DECLARE
  c_id UUID;
  sp1 UUID; sp2 UUID; sp3 UUID; sp4 UUID; sp5 UUID;
BEGIN
  INSERT INTO public.courses (name, description, icon)
  VALUES ('Oracle Fusion Cloud Applications PaaS Practice', 'Comprehensive 50-question practice exam covering SDLC, AI/ML, OCI Architect, Networking, DevOps, Kubernetes, and Autonomous Database.', 'shield')
  RETURNING id INTO c_id;

  INSERT INTO public.subtopics (course_id, name, order_index) VALUES (c_id, 'SDLC & Agile Development', 1) RETURNING id INTO sp1;
  INSERT INTO public.subtopics (course_id, name, order_index) VALUES (c_id, 'AI/ML & Natural Language Processing', 2) RETURNING id INTO sp2;
  INSERT INTO public.subtopics (course_id, name, order_index) VALUES (c_id, 'OCI Compute & Storage Architecture', 3) RETURNING id INTO sp3;
  INSERT INTO public.subtopics (course_id, name, order_index) VALUES (c_id, 'Networking, VCN & Security', 4) RETURNING id INTO sp4;
  INSERT INTO public.subtopics (course_id, name, order_index) VALUES (c_id, 'DevOps, Kubernetes & Autonomous DB', 5) RETURNING id INTO sp5;

  -- Questions for sp1
  INSERT INTO public.questions (subtopic_id, type, question_text, options, correct_answers, explanation, difficulty) VALUES
  (sp1, 'mcq', 'In the context of assigning multi-agent systems, what is the benefit of using agents with different model sizes and providers?', '["It allows agents to work on the same task simultaneously.", "It helps balance trade-offs between speed and output quality.", "It guarantees a single provider will always offer the best performance.", "It forces all agents to use the same model for consistency."]'::jsonb, '[1]'::jsonb, 'Using different models lets a system route simple work to faster, cheaper models and complex work to stronger models. Provider diversity can also improve resilience and reduce dependence on one model.', 'medium'),
  (sp1, 'mcq', 'What is the Agile principle that promotes face-to-face communication over written documents?', '["Working software is the primary measure of progress.", "Customer collaboration over contract negotiation.", "Continuous delivery.", "Self-organizing teams."]'::jsonb, '[1]'::jsonb, 'Among the listed choices, customer collaboration most closely emphasizes direct human communication instead of documentation-heavy interaction. The exact Agile value is "Individuals and interactions over processes and tools," but it is not offered.', 'medium'),
  (sp1, 'mcq', 'A company wants to eliminate manual deployment errors. What DevOps practice should it implement?', '["Manual deployments.", "Extended testing phases.", "Isolated team environments.", "Automated deployment pipelines."]'::jsonb, '[3]'::jsonb, 'Automated pipelines make deployment steps repeatable and reduce mistakes caused by manual execution. They also improve consistency, traceability, and release speed. Questions 4-30', 'medium'),
  (sp1, 'mcq', 'Reverse engineering involves generating the functional description, user stories from which of the following?', '["Functional architecture of the application", "Application code base", "Functional and technical architecture of the application", "Test scenarios and script documents"]'::jsonb, '[1]'::jsonb, 'Reverse engineering starts from an existing application or its source code and derives higher-level functional or design information. Therefore, the application code base is the input source.', 'medium'),
  (sp1, 'mcq', 'In the SDLC, what is the role of a Project Manager during the Testing phase?', '["To design test cases", "To ensure testing is completed on time and within scope", "To execute tests", "To code the software"]'::jsonb, '[1]'::jsonb, 'The Project Manager coordinates schedule, resources, risks, and scope during testing. Test design and execution are normally performed by QA or testing roles.', 'medium');

  -- Questions for sp2
  INSERT INTO public.questions (subtopic_id, type, question_text, options, correct_answers, explanation, difficulty) VALUES
  (sp2, 'mcq', 'As an AI/ML architect, you are analyzing a massive dataset of customer reviews from various sources, such as social media, surveys, and e-commerce platforms. The reviews range from single words to paragraphs and contain a mix of standard English, slang, abbreviations, and potentially emojis. What combination of techniques is most effective for transforming this noisy customer review data?', '["Represent reviews with pre-trained word embeddings, focusing on dimensionality reduction using techniques like PCA", "Apply text normalization, tokenization, stop-word removal, and consider lemmatization or stemming", "Utilize part-of-speech tagging, dependency parsing, and named-entity recognition to extract key information", "Focus on removing emojis, applying aggressive stemming, and building a custom regular-expression filter for identifying profanity"]'::jsonb, '[1]'::jsonb, 'This combination cleans inconsistent text, separates tokens, removes common low-information words, and normalizes word forms. It is the most generally appropriate preprocessing pipeline for noisy reviews.', 'medium'),
  (sp2, 'mcq', 'As an AI/ML architect, you are starting a new NLP project that will involve training large language models on a substantial dataset. You will need significant computational resources and want to streamline the setup process as much as possible. What approach is the most suitable for this project, considering efficiency and resource requirements?', '["Utilize a free Colab notebook and install all required NLP libraries and dependencies manually at the start of each session", "Upgrade to Colab Pro for priority access to powerful GPUs/TPUs, longer runtimes, and increased RAM", "Spin up a Google Cloud virtual machine instance, install necessary libraries, and use it for your project instead of Colab", "Create a standard Colab notebook and connect it to your local machine runtime for increased computational power"]'::jsonb, '[1]'::jsonb, 'Colab Pro directly provides stronger accelerators, longer sessions, and more memory with minimal setup. It best balances computational needs with convenience.', 'medium'),
  (sp2, 'mcq', 'As an AI/ML architect, you have fine-tuned a BERT model on a specialized dataset for identifying misinformation in social media posts. You want to make your model easily accessible to other researchers working on this problem. What sequence of steps correctly accomplishes this goal?', '["Fine-tune the BERT model, save the model weights locally, and share them through a personal website with instructions for loading them", "Push the pre-trained BERT model without fine-tuning to the Hugging Face Hub, providing a brief description of its general capabilities", "Create a detailed README describing the fine-tuning process and dataset, then upload the model weights and README to a code repository", "Fine-tune the BERT model, create a model card with clear documentation, and push it to the Hugging Face Hub using the Transformers library"]'::jsonb, '[3]'::jsonb, 'The Hugging Face Hub is designed for model hosting, versioning, documentation, and direct reuse through Transformers. A model card explains the dataset, intended use, and limitations.', 'medium'),
  (sp2, 'mcq', 'As an AI/ML architect, you have trained several text summarization models on a dataset of news articles. You need a way to automatically compare their outputs to human-written reference summaries and track progress during development. What use of ROUGE is most appropriate for this evaluation task?', '["Utilize ROUGE-L with a large N-gram size to directly measure the similarity between full generated and reference summaries", "Calculate ROUGE-1, ROUGE-2, and ROUGE-L for a comprehensive assessment", "Focus exclusively on ROUGE-1 to prioritize the fluency and preservation of longer, more meaningful word sequences in the summaries", "Calculate a weighted average of ROUGE scores, giving more importance to ROUGE-2 to emphasize bigram matching"]'::jsonb, '[1]'::jsonb, 'ROUGE-1 measures unigram overlap, ROUGE-2 measures bigram overlap, and ROUGE-L captures longest-common-subsequence similarity. Together they provide a broader evaluation than any single metric.', 'medium');

  -- Questions for sp3
  INSERT INTO public.questions (subtopic_id, type, question_text, options, correct_answers, explanation, difficulty) VALUES
  (sp3, 'mcq', 'In XYZ Inc. Oracle Cloud Infrastructure environment, you have an object in a bucket. The object was last modified 4 months ago. You create a retention rule and specify a duration of 1 year. Which statement is correct?', '["You will be able to modify or delete the object for the next 12 months", "You will be able to modify or delete the object for the next 4 months", "You will not be able to modify or delete the object for the next 12 months", "You will not be able to modify or delete the object for the next 8 months"]'::jsonb, '[3]'::jsonb, 'The one-year retention duration is calculated from the object''s last modification time. Since four months have already elapsed, eight months of protection remain.', 'medium'),
  (sp3, 'mcq', 'As a cloud architect, which compute capacity type would you use to run Oracle Cloud Infrastructure compute virtual machine instances on dedicated servers that are single tenant and not shared with other customers?', '["Preemptible Instances", "Exclusive Virtual Machine Hosts", "Dedicated Virtual Machine Hosts", "Capacity Reservation"]'::jsonb, '[2]'::jsonb, 'Dedicated VM Hosts provide a single-tenant physical server for running VM instances. The host is not shared with other customers.', 'medium'),
  (sp3, 'mcq', 'In an XYZ Inc. Oracle Cloud Infrastructure environment, what would you create to make a point-in-time disk-to-disk deep copy of an existing block volume without needing to go through the backup and restore process?', '["A twin", "A replica", "A prototype", "A backup"]'::jsonb, '[0]'::jsonb, 'OCI Block Volume uses a clone for a point-in-time disk-to-disk deep copy without backup and restore. The displayed options omit the correct answer.', 'medium'),
  (sp3, 'mcq', 'In an XYZ Inc. Oracle Cloud Infrastructure environment, which volume attachment type would you use to attach a block volume to a VM instance to get better IOPS performance?', '["iSCSI", "SMB", "Paravirtualized", "NFS"]'::jsonb, '[0]'::jsonb, 'The course material identifies iSCSI as the preferred attachment type when better IOPS performance is required. Paravirtualized attachment is simpler but does not provide the same performance choice here.', 'medium'),
  (sp3, 'mcq', 'As a cloud architect, which Oracle Cloud Infrastructure offering would you use to encrypt and isolate in-use data and applications processing that data?', '["Secret Computing", "Privileged Computing", "Confidential Computing", "Private Computing"]'::jsonb, '[2]'::jsonb, 'Confidential Computing protects data while it is actively being processed. It isolates in-use data and the applications working on it.', 'medium'),
  (sp3, 'mcq', 'As a cloud architect, which feature should you enable in Object Storage service to monitor data access patterns and automatically move objects larger than 1 MiB out of the Standard tier into the more cost-effective Infrequent Access tier?', '["Auto-Tiering", "Auto-Change", "Auto-Transition", "Auto-Move"]'::jsonb, '[0]'::jsonb, 'Auto-Tiering monitors access patterns and automatically moves eligible objects from Standard to Infrequent Access. This reduces cost without manual lifecycle management.', 'medium'),
  (sp3, 'mcq', 'In an ABC Inc. Oracle Cloud Infrastructure environment, you create a file system and add a 1 GB file. You then take a snapshot of the file system. What would be the total meteredBytes shown by the File Storage service after the hourly update cycle is completed?', '["2 GB", "1.5 GB", "0.5 GB", "1 GB"]'::jsonb, '[3]'::jsonb, 'A snapshot initially references existing data rather than creating a complete duplicate. Therefore, the metered storage remains 1 GB until changed blocks consume additional space.', 'medium'),
  (sp3, 'mcq', 'In ABC Inc., you have an instance that cannot be live migrated. OCI schedules a maintenance due date within 14 to 16 days and sends you a notification. What would happen if you do not proactively reboot the instance before the due date?', '["OCI will terminate the instance", "OCI does not take any action", "OCI will send you another notification to reboot", "The instance is either reboot migrated or rebuilt in place for you"]'::jsonb, '[3]'::jsonb, 'For a non-live-migratable instance, OCI handles maintenance by reboot migration or rebuilding it in place. This occurs if the customer does not proactively reboot before the deadline.', 'medium'),
  (sp3, 'mcq', 'ABC Inc. is setting up a new Oracle Cloud Infrastructure environment and anticipates managing a large number of users with fine-grained access control. It also plans to integrate on-premises or cloud-based Oracle and non-Oracle applications. Which OCI IAM identity domain type best meets these requirements?', '["External User", "Oracle Apps", "Premium", "Free"]'::jsonb, '[2]'::jsonb, 'The Premium identity-domain type supports large user populations, fine-grained controls, and broad application integration. It is the best fit for the stated enterprise requirements.', 'medium');

  -- Questions for sp4
  INSERT INTO public.questions (subtopic_id, type, question_text, options, correct_answers, explanation, difficulty) VALUES
  (sp4, 'mcq', 'In an XYZ Inc. Oracle Cloud Infrastructure environment, which storage tier should you use to make the solution more cost effective for data that is seldom accessed but requires a long retention period?', '["Reduced Redundancy", "Archive", "Standard", "Infrequent Access"]'::jsonb, '[1]'::jsonb, 'Archive Storage is intended for data that is rarely accessed and retained for long periods. It offers the lowest storage cost among the listed OCI tiers.', 'medium'),
  (sp4, 'mcq', 'As a cloud architect, what Traffic Management Steering Policy do you need for distributing traffic over several servers to optimize performance?', '["ASN Steering", "Load Balancer", "IP Prefix Steering", "Geolocation"]'::jsonb, '[1]'::jsonb, 'The Load Balancer steering policy distributes DNS traffic across multiple endpoints. This improves utilization and application performance.', 'medium'),
  (sp4, 'mcq', 'As a cloud architect, what happens if you create a VCN with the same CIDR prefix as another VCN in the same tenancy, region, and compartment?', '["You will not be able to add subnets to this VCN", "Nothing. However, you will not be able to peer them", "Nothing. However, DNS services will not allow you to create DNS zones", "Ownership of the public IPv4 CIDR block or IPv6 prefix registered with a Web Hosting Provider"]'::jsonb, '[1]'::jsonb, 'OCI allows overlapping VCN CIDRs to be created. However, overlapping CIDR ranges prevent the VCNs from being peered.', 'medium'),
  (sp4, 'mcq', 'As a cloud architect, which feature should you use to upload a 2 TiB object to Object Storage and have the flexibility to pause between uploads of individual parts and resume when your schedule allows?', '["Splitpart uploads", "Split upload", "Multipart uploads", "Simultaneous upload"]'::jsonb, '[2]'::jsonb, 'Multipart upload divides a large object into independently uploaded parts. Individual parts can be retried, paused, and resumed before final assembly.', 'medium'),
  (sp4, 'mcq', 'As a cloud architect, what is required for importing a public IPv4 CIDR block or IPv6 prefix into Oracle Cloud Infrastructure?', '["Ownership of the public IPv4 CIDR block or IPv6 prefix registered with a Regional Internet Registry (RIR)", "Ownership of the public IPv4 CIDR block or IPv6 prefix registered with a Domain Name System (DNS) service", "Ownership of the public IPv4 CIDR block or IPv6 prefix registered with a Domain Name Registrar", "PUBLIC writes host entries to disk"]'::jsonb, '[0]'::jsonb, 'OCI Bring Your Own IP requires proof that the address range belongs to the customer. Ownership is established through the relevant Regional Internet Registry.', 'medium'),
  (sp4, 'mcq', 'In ABC Inc., an aspiring software designer wants to know more about DevOps as a Service. Which option best describes DevOps as a Service?', '["It is a service that primarily focuses on deploying and maintaining cloud infrastructure for System Administrators", "It is a CI/CD platform that enables developers to automate and streamline the software delivery life cycle", "It is a service that provides tools and resources for various IT professionals to build and manage cloud systems", "It is a service that operates two separate pipelines concurrently to support multiple development teams"]'::jsonb, '[1]'::jsonb, 'DevOps as a Service provides CI/CD capabilities for automating build, test, and deployment workflows. Its purpose is to streamline software delivery.', 'medium'),
  (sp4, 'mcq', 'Within the architecture of Kubernetes, various components collaborate to manage containerized workloads efficiently. Which component is NOT a core part of Kubernetes architecture?', '["Kube-proxy, responsible for network proxying and load balancing across application services", "Kubelet, responsible for communicating with the Kubernetes master and managing containers on a node", "Docker Swarm, an alternative container orchestration platform developed by Docker Inc.", "etcd, a key-value store used by Kubernetes for cluster data"]'::jsonb, '[2]'::jsonb, 'Kube-proxy, kubelet, and etcd are Kubernetes components. Docker Swarm is a separate container-orchestration platform.', 'medium'),
  (sp4, 'mcq', 'How do OCI DevOps Deployment pipelines reduce the risk and complexity of production applications?', '["By eliminating down time of production applications", "By reducing change-driven errors introduced by manual deployments", "By working with existing Git repositories and CI systems", "By scaling builds with service-managed build runners"]'::jsonb, '[1]'::jsonb, 'Automated deployment pipelines replace error-prone manual steps with repeatable processes. This lowers operational risk and deployment complexity.', 'medium'),
  (sp4, 'mcq', 'XYZ Inc. is a software company experiencing performance issues with its monolithic architecture for an e-commerce website. In the context of software architecture, what is a microservice?', '["A style of design for enterprise systems based on a loosely coupled component architecture", "A small program that represents discrete logic that executes within a well-defined boundary on dedicated hardware", "A cloud-based service for testing and deploying microcode", "A software framework for automating user interface testing"]'::jsonb, '[0]'::jsonb, 'Microservices organize an application as small, loosely coupled services. These services can be developed, deployed, and scaled independently.', 'medium'),
  (sp4, 'mcq', 'As a DevOps Engineer working on containerizing an application on OCI, which two statements are FALSE about OCI Container Instances? (Choose two.)', '["You can configure the number of resources that a container consumes in absolute values or percentages", "While configuring container instances, you can set environment variables used by the container", "The amount of time the container instance waits for the OS to shut down before powering off is managed internally", "By default, the container can use only 50% of resources in the container instance"]'::jsonb, '[2]'::jsonb, 'OCI allows configuration of container resource allocation and shutdown behavior. Therefore, the claims that shutdown timing is only internally managed and that containers default to a 50% resource limit are false.', 'medium'),
  (sp4, 'mcq', 'Kubernetes is an open-source platform designed for automating deployment, scaling, and management of containerized applications. What is the primary objective of Kubernetes?', '["Kubernetes aims to streamline container orchestration, ensuring efficient deployment and management of containerized applications across a cluster of machines", "Kubernetes primarily focuses on facilitating CI/CD pipelines", "Kubernetes focuses on providing a user-friendly interface for configuring containerized environments", "Kubernetes primarily emphasizes load balancing to distribute incoming traffic among containers"]'::jsonb, '[0]'::jsonb, 'Kubernetes automates deployment, scaling, scheduling, and management of containerized workloads. CI/CD and load balancing are related capabilities, not its complete primary objective.', 'medium'),
  (sp4, 'mcq', 'In XYZ Inc., a DevOps engineer is asked to remove a stage from the build pipeline. What happens to the associated resources when the stage is removed?', '["Associated resources are removed but the stage is still available", "Associated resources are marked for deletion but not deleted until manually deleted", "Associated resources and the stage are both removed", "Associated resources are still available but the stage is marked for deletion"]'::jsonb, '[2]'::jsonb, 'According to the supplied course answer, deleting the pipeline stage also removes its associated resources. Both are removed together. Questions 31-50', 'medium'),
  (sp4, 'mcq', 'In XYZ Inc., an application continuously logs sensitive information that needs restricted access. What is a possible solution?', '["By default, OCI Logging identifies and restricts access to sensitive logs", "Choose separate logs group for sensitive logs and use IAM policies", "Transition all sensitive logs into Object Storage using Service Connector", "Configure a Notifications Topic to alert when sensitive data is logged"]'::jsonb, '[1]'::jsonb, 'A separate log group creates a distinct authorization boundary. IAM policies can then limit access to only approved users or groups.', 'medium'),
  (sp4, 'mcq', 'ABC Inc. is incorporating DevSecOps practices to improve software development and security functions. What is the recommended approach to security functions in the DevSecOps process?', '["Complete reliance on cloud service providers for security", "Manual processes to ensure more control", "Strong governance including use of automated tools", "Independent security teams separate from DevOps"]'::jsonb, '[2]'::jsonb, 'DevSecOps integrates security into delivery workflows through governance and automation. Isolated teams and manual-only processes slow feedback and increase inconsistency.', 'medium'),
  (sp4, 'mcq', 'In XYZ Inc., a network administrator provisioned an OCI Load Balancer and views it via the Web GUI. What can the Move Resource feature be used for?', '["To move the Load Balancer to another compartment", "To move the Load Balancer to another region", "To convert the Load Balancer to a Network Load Balancer", "To move the Load Balancer to another subnet"]'::jsonb, '[0]'::jsonb, 'Move Resource changes the compartment that contains the load balancer. It does not convert the service type or move it across regions or subnets.', 'medium'),
  (sp4, 'mcq', 'ABC Inc. requires seamless communication over IPv6 and needs to assign its own IPv6 addresses to resources in OCI. Which OCI service should be used to manage custom IPv6 addresses and provide routing?', '["Oracle Network Path Analyzer", "Oracle Cloud FastConnect", "Oracle Cloud Virtual Network", "Oracle Cloud Load Balancer"]'::jsonb, '[2]'::jsonb, 'A VCN manages IP addressing, subnets, and routing for OCI resources. It is the correct service for custom IPv6 address assignment and routing.', 'medium'),
  (sp4, 'mcq', 'In XYZ Inc., a DevOps team needs to interconnect an on-premises network to OCI resources such as a managed database in a private subnet. The budget and bandwidth requirements are minimal, so VPN is selected. Which OCI object represents the customer router public IP address?', '["Internet Gateway", "Customer Premises Equipment", "IPSec Tunnel", "Virtual Network Interface Card"]'::jsonb, '[1]'::jsonb, 'A CPE object represents the customer-side router in an OCI Site-to-Site VPN configuration. The IPSec tunnels then connect that CPE to the OCI DRG.', 'medium');

  -- Questions for sp5
  INSERT INTO public.questions (subtopic_id, type, question_text, options, correct_answers, explanation, difficulty) VALUES
  (sp5, 'mcq', 'ABC Inc. wants to interconnect OCI with another cloud provider in London so that resources can use ADW machine-learning capabilities. The connection should be quick to provision, high bandwidth, and predictable. Which cloud provider should be chosen?', '["Amazon Web Services", "Google Cloud Platform", "Digital Ocean", "Azure Cloud"]'::jsonb, '[1]'::jsonb, 'The supplied networking course identifies Google Cloud Platform for this OCI interconnection scenario. It meets the stated rapid-provisioning and predictable high-bandwidth requirements.', 'medium'),
  (sp5, 'mcq', 'What is a key difference between Dynamic Routing Gateway and Local Peering Gateway when implementing Cross-Tenancy Peering?', '["Local Peering Gateway can have a Cross-Tenancy Attachment", "Dynamic Routing Gateway can have a Cross-Tenancy Attachment", "Dynamic Routing Gateway needs the acceptor to be in either tenancy", "Local Peering Gateway needs the requestor to be in either tenancy"]'::jsonb, '[1]'::jsonb, 'A DRG supports a cross-tenancy attachment. This is the distinguishing capability identified by the course material.', 'medium'),
  (sp5, 'mcq', 'In Oracle Cloud Infrastructure, which service controls the flow of traffic between different network destinations?', '["Network Security Group associated with a subnet", "Virtual Cloud Network Security List", "Route Table associated with a subnet", "Identity and Access Management"]'::jsonb, '[2]'::jsonb, 'A route table contains rules that direct traffic to network destinations through gateways or other targets. Security lists and NSGs allow or deny traffic but do not choose the route.', 'medium'),
  (sp5, 'mcq', 'Which Oracle Cloud Infrastructure service enables an instance to connect to a Virtual Cloud Network and determines how the instance connects with endpoints inside and outside the VCN?', '["Virtual Network Interface Card", "Internet Gateway", "Route Table", "Network Security Group"]'::jsonb, '[0]'::jsonb, 'A VNIC attaches a compute instance to a VCN. It provides the instance''s network interface and connectivity configuration.', 'medium'),
  (sp5, 'mcq', 'What is the key distinction between stateful and stateless security rules in Oracle Cloud Infrastructure?', '["Stateful rules track the state of network connections while stateless rules do not", "Stateless rules are more secure and provide enhanced encryption", "Stateless rules apply only to inbound traffic while stateful rules apply to both inbound and outbound traffic", "Stateful rules are defined at VCN level while stateless rules are defined at subnet level"]'::jsonb, '[0]'::jsonb, 'Stateful rules automatically account for return traffic by tracking connection state. Stateless rules evaluate each packet independently and require explicit rules for both directions.', 'medium'),
  (sp5, 'mcq', 'As an Autonomous Database administrator, what is the main use of REST APIs?', '["Monitoring", "Monitoring, DevOps", "Monitoring, Development", "Monitoring, DevOps, Development"]'::jsonb, '[3]'::jsonb, 'REST APIs support operational monitoring, automation and DevOps workflows, and application development. The course explicitly lists all three use cases.', 'medium'),
  (sp5, 'mcq', 'Which two statements are true about a cloned Autonomous Database? (Choose two.)', '["It can contain only the metadata of the source Autonomous Database", "It is a refreshable read-write clone of the source Autonomous Database", "It is a refreshable read-only clone of the source Autonomous Database", "It can contain only the data of the source Autonomous Database"]'::jsonb, '[2]'::jsonb, 'The supplied course answer recognizes a refreshable read-only clone and a data-only clone. The read-write and metadata-only statements are not the expected selections.', 'medium'),
  (sp5, 'mcq', 'As an Autonomous Database administrator, what does Database Migration service use for migration?', '["Backup Cloud Module", "RMAN Backup", "GoldenGate", "Data Guard"]'::jsonb, '[2]'::jsonb, 'The course material states that Database Migration service uses GoldenGate. GoldenGate supports replication-based migration with reduced downtime.', 'medium'),
  (sp5, 'mcq', 'Which three actions can you perform from the Autonomous Container Database details page? (Choose three.)', '["Change the maintenance schedule", "Move the CDB to a different compartment", "Change the backup retention policy for the CDB", "Restart the CDB E. Change the maintenance schedule"]'::jsonb, '[1]'::jsonb, 'The verified course selections are moving the CDB, changing its backup retention policy, and restarting it. The screenshot duplicates the maintenance-schedule option, but it is not one of the expected answers.', 'medium'),
  (sp5, 'mcq', 'Which two methods can you use to migrate an on-premises database to Oracle Autonomous Database? (Choose two.)', '["GoldenGate", "RMAN", "Data Pump", "Data Guard"]'::jsonb, '[0]'::jsonb, 'GoldenGate supports replication-based migration, while Data Pump supports logical export and import. RMAN and Data Guard are not the two expected methods for this question.', 'medium'),
  (sp5, 'mcq', 'With which activities does Oracle Machine Learning allow access to data in Autonomous Database?', '["Data ingestion and selection only", "Data ingestion and selection, data viewing and discovery, and data analysis", "Data viewing and discovery, and data ingestion and selection", "Data ingestion and selection, and data viewing and discovery"]'::jsonb, '[1]'::jsonb, 'Oracle Machine Learning supports the full workflow from accessing and selecting data to exploring and analyzing it. The most complete option is therefore correct.', 'medium'),
  (sp5, 'mcq', 'As an Autonomous Database administrator, which statement is true about Spatial Studio?', '["It is a fully managed service available in OCI", "It is a self-service application to create interactive maps", "It does not need additional resources", "It comes with an Autonomous Database at an additional cost"]'::jsonb, '[1]'::jsonb, 'Spatial Studio is a self-service application for visualizing spatial data and building interactive maps. The other descriptions do not match the course definition.', 'medium'),
  (sp5, 'mcq', 'For which three cloud services does DBMS_CLOUD provide support for loading data from files to tables in Autonomous Database? (Choose three.)', '["Amazon AWS S3", "OCI Object Storage Classic", "OCI Object Storage", "Dell EMC Elastic Cloud Storage"]'::jsonb, '[0]'::jsonb, 'DBMS_CLOUD supports Amazon S3, OCI Object Storage Classic, and OCI Object Storage for this loading workflow. Dell EMC Elastic Cloud Storage is not one of the three course answers.', 'medium'),
  (sp5, 'mcq', 'Which statement is true about moving Autonomous Database resources?', '["After a resource is moved to a new tenant, inherent policies apply immediately and affect access", "After a resource is moved to a new compartment, inherent policies apply immediately and affect access", "After a resource is moved to a new tenant, inherent policies apply later and affect access", "After a resource is moved to a new compartment, inherent policies apply later and affect access"]'::jsonb, '[1]'::jsonb, 'When an Autonomous Database resource is moved, the destination compartment''s policies take effect immediately. Access can therefore change as soon as the move completes.', 'medium'),
  (sp5, 'mcq', 'As an Autonomous Database administrator, which procedure do you use to load data directly into existing Autonomous Database tables?', '["DBMS_CLOUD.COPY_DATA", "DBMS_CLOUD.LIST_FILES", "DBMS_CLOUD.PUT_OBJECT", "DBMS_CLOUD.CREATE_EXTERNAL_TABLE"]'::jsonb, '[0]'::jsonb, 'DBMS_CLOUD.COPY_DATA loads data directly into an existing database table. CREATE_EXTERNAL_TABLE instead creates an external table over files.', 'medium');

END $$;
