-- Seed SQL for Oracle PaaS MCQ 1 Practice Exam (50 Questions)

DO $$
DECLARE
  c_id UUID;
  sp1 UUID; sp2 UUID; sp3 UUID; sp4 UUID; sp5 UUID;
BEGIN
  -- Insert Course: Oracle PaaS MCQ 1
  INSERT INTO public.courses (name, description, icon)
  VALUES ('Oracle PaaS MCQ 1 Practice Exam', 'Official MCQ 1 milestone practice exam covering 50 questions across SDLC, AI/ML, OCI Architect, Networking, DevOps, Kubernetes, and Autonomous Database.', 'trophy')
  RETURNING id INTO c_id;

  INSERT INTO public.subtopics (course_id, name, order_index) VALUES (c_id, 'MCQ 1: SDLC & Agile Development', 1) RETURNING id INTO sp1;
  INSERT INTO public.subtopics (course_id, name, order_index) VALUES (c_id, 'MCQ 1: AI/ML & Natural Language Processing', 2) RETURNING id INTO sp2;
  INSERT INTO public.subtopics (course_id, name, order_index) VALUES (c_id, 'MCQ 1: OCI Compute & Storage Architecture', 3) RETURNING id INTO sp3;
  INSERT INTO public.subtopics (course_id, name, order_index) VALUES (c_id, 'MCQ 1: Networking, VCN & Security', 4) RETURNING id INTO sp4;
  INSERT INTO public.subtopics (course_id, name, order_index) VALUES (c_id, 'MCQ 1: DevOps, Kubernetes & Autonomous DB', 5) RETURNING id INTO sp5;

  -- Questions for sp1
  INSERT INTO public.questions (subtopic_id, type, question_text, options, correct_answers, explanation, difficulty) VALUES
  (sp1, 'mcq', 'In the context of assigning multi-agent systems, what is the benefit of using agents with different model sizes and providers?', '["It allows agents to work on the same task simultaneously.", "It helps balance trade-offs between speed and output quality.", "It guarantees a single provider will always offer the best performance.", "It forces all agents to use the same model for consistency."]'::jsonb, '[1]'::jsonb, 'Using different models lets a system route simple work to faster, cheaper models and complex work to stronger models. Provider diversity can also improve resilience and reduce dependence on one model.', 'medium'),
  (sp1, 'mcq', 'What is the Agile principle that promotes face-to-face communication over written documents?', '["Working software is the primary measure of progress.", "Customer collaboration over contract negotiation.", "Continuous delivery.", "Self-organizing teams."]'::jsonb, '[1]'::jsonb, 'Among the listed choices, customer collaboration most closely emphasizes direct human communication instead of documentation-heavy interaction. The exact Agile value is "Individuals and interactions over processes and tools," but it is not offered.', 'medium'),
  (sp1, 'mcq', 'A company wants to eliminate manual deployment errors. What DevOps practice should it implement?', '["Manual deployments.", "Extended testing phases.", "Isolated team environments.", "Automated deployment pipelines."]'::jsonb, '[3]'::jsonb, 'Automated pipelines make deployment steps repeatable and reduce mistakes caused by manual execution. They also improve consistency, traceability, and release speed. Questions 4-30', 'medium'),
  (sp1, 'mcq', 'Reverse engineering involves generating the functional description, user stories from which of the following?', '["Functional architecture of the application", "Application code base", "Functional and technical architecture of the application", "Test scenarios and script documents"]'::jsonb, '[1]'::jsonb, 'Reverse engineering starts from an existing application or its source code and derives higher-level functional or design information. Therefore, the application code base is the input source.', 'medium'),
  (sp1, 'mcq', 'In the SDLC, what is the role of a Project Manager during the Testing phase?', '["To design test cases", "To ensure testing is completed on time and within scope", "To execute tests", "To code the software"]'::jsonb, '[1]'::jsonb, 'The Project Manager coordinates schedule, resources, risks, and scope during testing. Test design and execution are normally performed by QA or testing roles.', 'medium');

  -- Questions for sp2
  INSERT INTO public.questions (subtopic_id, type, question_text, options, correct_answers, explanation, difficulty) VALUES
  (sp2, 'mcq', 'As an AI/ML architect, you are analyzing a massive dataset of customer reviews from various sources, such as social media, surveys, and e-commerce platforms. The reviews range from single words to paragraphs and contain a mix of standard English, slang, abbreviations, and potentially emojis. What combination of techniques is most effective for transforming this noisy customer review data?', '["Represent reviews with pre-trained word embeddings, focusing on dimensionality reduction using techniques like PCA", "Apply text normalization, tokenization, stop-word removal, and consider lemmatization or stemming", "Utilize part-of-speech tagging, dependency parsing, and named-entity recognition to extract key information", "Focus on removing emojis, applying aggressive stemming, and building a custom regular-expression filter for identifying profanity"]'::jsonb, '[1]'::jsonb, 'This combination cleans inconsistent text, separates tokens, removes common low-information words, and normalizes word forms. It is the most generally appropriate preprocessing pipeline for noisy reviews.', 'medium'),
  (sp2, 'mcq', 'As an AI/ML architect, you are starting a new NLP project that will involve training large language models on a substantial dataset. You will need significant computational resources and want to streamline the setup process as much as possible. What approach is the most suitable for this project, considering efficiency and resource requirements?', '["Utilize a free Colab notebook and install all required NLP libraries and dependencies manually at the start of each session", "Upgrade to Colab Pro for priority access to powerful GPUs/TPUs, longer runtimes, and increased RAM", "Spin up a Google Cloud virtual machine instance, install necessary libraries, and use it for your project instead of Colab", "Create a standard Colab notebook and connect it to your local machine runtime for increased computational power"]'::jsonb, '[1]'::jsonb, 'Colab Pro directly provides stronger accelerators, longer sessions, and more memory with minimal setup. It best balances computational needs with convenience.', 'medium'),
  (sp2, 'mcq', 'As an AI/ML architect, you have fine-tuned a BERT model on a specialized dataset for identifying misinformation in social media posts. You want to make your model easily accessible to other researchers working on this problem. What sequence of steps correctly accomplishes this goal?', '["Fine-tune the BERT model, save the model weights locally, and share them through a personal website with instructions for loading them", "Push the pre-trained BERT model without fine-tuning to the Hugging Face Hub, providing a brief description of its general capabilities", "Create a detailed README describing the fine-tuning process and dataset, then upload the model weights and README to a code repository", "Fine-tune the BERT model, create a model card with clear documentation, and push it to the Hugging Face Hub using the Transformers library"]'::jsonb, '[3]'::jsonb, 'The Hugging Face Hub is designed for model hosting, versioning, documentation, and direct reuse through Transformers. A model card explains the dataset, intended use, and limitations.', 'medium'),
  (sp2, 'mcq', 'As an AI/ML architect, you have trained several text summarization models on a dataset of news articles. You need a way to automatically compare their outputs to human-written reference summaries and track progress during development. What use of ROUGE is most appropriate for this evaluation task?', '["Utilize ROUGE-L with a large N-gram size to directly measure the similarity between full generated and reference summaries", "Calculate ROUGE-1, ROUGE-2, and ROUGE-L for a comprehensive assessment", "Focus exclusively on ROUGE-1 to prioritize the fluency and preservation of longer, more meaningful word sequences in the summaries", "Calculate a weighted average of ROUGE scores, giving more importance to ROUGE-2 to emphasize bigram matching"]'::jsonb, '[1]'::jsonb, 'ROUGE-1 measures unigram overlap, ROUGE-2 measures bigram overlap, and ROUGE-L captures longest-common-subsequence similarity. Together they provide a broader evaluation than any single metric.', 'medium');

  -- Questions for sp3
  INSERT INTO public.questions (subtopic_id, type, question_text, options, correct_answers, explanation, difficulty) VALUES
  (sp3, 'mcq', 'In XYZ Inc. Oracle Cloud Infrastructure environment, you have an object in a bucket. The object was last modified 4 months ago. You create a retention rule and specify a duration of 1 year. Which statement is correct?', '["You will be able to modify or delete the object for the next 12 months", "You will be able to modify or delete the object for the next 4 months", "You will not be able to modify or delete the object for the next 12 months", "You will not be able to modify or delete the object for the next 8 months"]'::jsonb, '[3]'::jsonb, 'The one-year retention duration is calculated from the object''s last modification time. Since four months have already elapsed, eight months of protection remain.', 'medium'),
  (sp3, 'mcq', 'As a cloud architect, which compute capacity type would you use to run Oracle Cloud Infrastructure compute virtual machine instances on dedicated servers that are single tenant and not shared with other customers?', '["Preemptible Instances", "Exclusive Virtual Machine Hosts", "Dedicated Virtual Machine Hosts", "Capacity Reservation"]'::jsonb, '[2]'::jsonb, 'Dedicated VM Hosts provide a single-tenant physical server for running VM instances. The host is not shared with other customers.', 'medium'),
  (sp3, 'mcq', 'In an XYZ Inc. Oracle Cloud Infrastructure environment, what would you create to make a point-in-time disk-to-disk deep copy of an existing block volume without needing to go through the backup and restore process?', '["A twin", "A replica", "A prototype", "A backup"]'::jsonb, '[0]'::jsonb, 'OCI Block Volume uses a clone for a point-in-time disk-to-disk deep copy without backup and restore. The displayed options omit the correct answer.', 'medium'),
  (sp3, 'mcq', 'In an XYZ Inc. Oracle Cloud Infrastructure environment, which volume attachment type would you use to attach a block volume to a VM instance to get better IOPS performance?', '["iSCSI", "SMB", "Paravirtualized", "NFS"]'::jsonb, '[0]'::jsonb, 'The course material identifies iSCSI as the preferred attachment type when better IOPS performance is required. Paravirtualized attachment is simpler but does not provide the same performance choice here.', 'medium'),
  (sp3, 'mcq', 'As a cloud architect, which Oracle Cloud Infrastructure offering would you use to encrypt and isolate in-use data and applications processing that data?', '["Secret Computing", "Privileged Computing", "Confidential Computing", "Private Computing"]'::jsonb, '[2]'::jsonb, 'Confidential Computing protects data while it is actively being processed. It isolates in-use data and the applications working on it.', 'medium'),
  (sp3, 'mcq', 'As a cloud architect, which feature should you enable in Object Storage service to monitor data access patterns and automatically move objects larger than 1 MiB out of the Standard tier into the more cost-effective Infrequent Access tier?', '["Auto-Tiering", "Auto-Change", "Auto-Transition", "Auto-Move"]'::jsonb, '[0]'::jsonb, 'Auto-Tiering monitors access patterns and automatically moves eligible objects from Standard to Infrequent Access. This reduces cost without manual lifecycle management.', 'medium'),
  (sp3, 'mcq', 'In an ABC Inc. Oracle Cloud Infrastructure environment, you create a file system and add a 1 GB file. You then take a snapshot of the file system. What would be the total meteredBytes shown by the File Storage service after the hourly update cycle is completed?', '["2 GB", "1.5 GB", "0.5 GB", "1 GB"]'::jsonb, '[3]'::jsonb, 'A snapshot initially references existing data rather than creating a complete duplicate. Therefore, the metered storage remains 1 GB until changed blocks consume additional space.', 'medium'),
  (sp3, 'mcq', 'In ABC Inc., you have an instance that cannot be live migrated. OCI schedules a maintenance due date within 14 to 16 days and sends you a notification. What would happen if you do not proactively reboot the instance before the due date?', '["OCI will terminate the instance", "OCI does not take any action", "OCI will send you another notification to reboot", "The instance is either reboot migrated or rebuilt in place for you"]'::jsonb, '[3]'::jsonb, 'For a non-live-migratable instance, OCI handles maintenance by reboot migration or rebuilding it in place. This occurs if the customer does not proactively reboot before the deadline.', 'medium'),
  (sp3, 'mcq', 'ABC Inc. is setting up a new Oracle Cloud Infrastructure environment and anticipates managing a large number of users with fine-grained access control. It also plans to integrate on-premises or cloud-based Oracle and non-Oracle applications. Which OCI IAM identity domain type best meets these requirements?', '["External User", "Oracle Apps", "Premium", "Free"]'::jsonb, '[2]'::jsonb, 'The Premium identity-domain type supports large user populations, fine-grained controls, and broad application integration. It is the best fit for the stated enterprise requirements.', 'medium');

  -- Questions for sp4
  INSERT INTO public.questions (subtopic_id, type, question_text, options, correct_answers, explanation, difficulty) VALUES
  (sp4, 'mcq', 'In an XYZ Inc. Oracle Cloud Infrastructure environment, which storage tier should you use to make the solution more cost effective for data that is seldom accessed but requires a long retention period?', '["Reduced Redundancy", "Archive", "Standard", "Infrequent Access"]'::jsonb, '[1]'::jsonb, 'Archive Storage is intended for data that is rarely accessed and retained for long periods. It offers the lowest storage cost among the listed OCI tiers.', 'medium'),
  (sp4, 'mcq', 'As a cloud architect, what Traffic Management Steering Policy do you need for distributing traffic over several servers to optimize performance?', '["ASN Steering", "Load Balancer", "IP Prefix Steering", "Geolocation"]'::jsonb, '[1]'::jsonb, 'The Load Balancer steering policy distributes DNS traffic across multiple endpoints. This improves utilization and application performance.', 'medium'),
  (sp4, 'mcq', 'As a cloud architect, what happens if you create a VCN with the same CIDR prefix as another VCN in the same tenancy, region, and compartment?', '["You will not be able to add subnets to this VCN", "Nothing. However, you will not be able to peer them", "Nothing. However, DNS services will not allow you to create DNS zones", "Ownership of the public IPv4 CIDR block or IPv6 prefix registered with a Web Hosting Provider"]'::jsonb, '[1]'::jsonb, 'OCI allows overlapping VCN CIDRs to be created. However, overlapping CIDR ranges prevent the VCNs from being peered.', 'medium'),
  (sp4, 'mcq', 'As a cloud architect, which feature should you use to upload a 2 TiB object to Object Storage and have the flexibility to pause between uploads of individual parts and resume when your schedule allows?', '["Splitpart uploads", "Split upload", "Multipart uploads", "Simultaneous upload"]'::jsonb, '[2]'::jsonb, 'Multipart upload divides a large object into independently uploaded parts. Individual parts can be retried, paused, and resumed before final assembly.', 'medium'),
  (sp4, 'mcq', 'As a cloud architect, what is required for importing a public IPv4 CIDR block or IPv6 prefix into Oracle Cloud Infrastructure?', '["Ownership of the public IPv4 CIDR block or IPv6 prefix registered with a Regional Internet Registry (RIR)", "Ownership of the public IPv4 CIDR block or IPv6 prefix registered with a Domain Name System (DNS) service", "Ownership of the public IPv4 CIDR block or IPv6 prefix registered with a Domain Name Registrar", "PUBLIC writes host entries to disk"]'::jsonb, '[0]'::jsonb, 'OCI Bring Your Own IP requires proof that the address range belongs to the customer. Ownership is established through the relevant Regional Internet Registry.', 'medium'),
  (sp4, 'mcq', 'In ABC Inc., an aspiring software designer wants to know more about DevOps as a Service. Which option best describes DevOps as a Service?', '["It is a service that primarily focuses on deploying and maintaining cloud infrastructure for System Administrators", "It is a CI/CD platform that enables developers to automate and streamline the software delivery life cycle", "It is a service that provides tools and resources for various IT professionals to build and manage cloud systems", "It is a service that operates two separate pipelines concurrently to support multiple development teams"]'::jsonb, '[1]'::jsonb, 'DevOps as a Service provides CI/CD capabilities for automating build, test, and deployment workflows. Its purpose is to streamline software delivery.', 'medium'),
  (sp4, 'mcq', 'Within the architecture of Kubernetes, various components collaborate to manage containerized workloads efficiently. Which component is NOT a core part of Kubernetes architecture?', '["Kube-proxy, responsible for network proxying and load balancing across application services", "Kubelet, responsible for communicating with the Kubernetes master and managing containers on a node", "Docker Swarm, an alternative container orchestration platform developed by Docker Inc.", "etcd, a key-value store used by Kubernetes for cluster data"]'::jsonb, '[2]'::jsonb, 'Kube-proxy, kubelet, and etcd are Kubernetes components. Docker Swarm is a separate container-orchestration platform.', 'medium'),
  (sp4, 'mcq', 'How do OCI DevOps Deployment pipelines reduce the risk and complexity of production applications?', '["By eliminating down time of production applications", "By reducing change-driven errors introduced by manual deployments", "By working with existing Git repositories and CI systems", "By scaling builds with service-managed build runners"]'::jsonb, '[1]'::jsonb, 'Automated deployment pipelines replace error-prone manual steps with repeatable processes. This lowers operational risk and deployment complexity.', 'medium'),
  (sp4, 'mcq', 'XYZ Inc. is a software company experiencing performance issues with its monolithic architecture for an e-commerce website. In the context of software architecture, what is a microservice?', '["A style of design for enterprise systems based on a loosely coupled component architecture", "A small program that represents discrete logic that executes within a well-defined boundary on dedicated hardware", "A cloud-based service for testing and deploying microcode", "A software framework for automating user interface testing"]'::jsonb, '[0]'::jsonb, 'Microservices organize an application as small, loosely coupled services. These services can be developed, deployed, and scaled independently.', 'medium'),
  (sp4, 'mcq', 'As a DevOps Engineer working on containerizing an application on OCI, which two statements are FALSE about OCI Container Instances? (Choose two.)', '["You can configure the number of resources that a container consumes in absolute values or percentages", "While configuring container instances, you can set environment variables used by the container", "The amount of time the container instance waits for the OS to shut down before powering off is managed internally", "By default, the container can use only 50% of resources in the container instance"]'::jsonb, '[2]'::jsonb, 'OCI allows configuration of container resource allocation and shutdown behavior. Therefore, the claims that shutdown timing is only internally managed and that containers default to a 50% resource limit are false.', 'medium'),
  (sp4, 'mcq', 'Kubernetes is an open-source platform designed for automating deployment, scaling, and management of containerized applications. What is the primary objective of Kubernetes?', '["Kubernetes aims to streamline container orchestration, ensuring efficient deployment and management of containerized applications across a cluster of machines", "Kubernetes primarily focuses on facilitating CI/CD pipelines", "Kubernetes focuses on providing a user-friendly interface for configuring containerized environments", "Kubernetes primarily emphasizes load balancing to distribute incoming traffic among containers"]'::jsonb, '[0]'::jsonb, 'Kubernetes automates deployment, scaling, scheduling, and management of containerized workloads. CI/CD and load balancing are related capabilities, not its complete primary objective.', 'medium'),
  (sp4, 'mcq', 'In XYZ Inc., a DevOps engineer is asked to remove a stage from the build pipeline. What happens to the associated resources when the stage is removed?', '["Associated resources are removed but the stage is still available", "Associated resources are marked for deletion but not deleted until manually deleted", "Associated resources and the stage are both removed", "Associated resources are still available but the stage is marked for deletion"]'::jsonb, '[2]'::jsonb, 'According to the supplied course answer, deleting the pipeline stage also removes its associated resources. Both are removed together. Questions 31-50', 'medium'),
  (sp4, 'mcq', 'In XYZ Inc., an application continuously logs sensitive information that needs restricted access. What is a possible solution?', '["By default, OCI Logging identifies and restricts access to sensitive logs", "Choose separate logs group for sensitive logs and use IAM policies", "Transition all sensitive logs into Object Storage using Service Connector", "Configure a Notifications Topic to alert when sensitive data is logged"]'::jsonb, '[1]'::jsonb, 'A separate log group creates a distinct authorization boundary. IAM policies can then limit access to only approved users or groups.', 'medium'),
  (sp4, 'mcq', 'ABC Inc. is incorporating DevSecOps practices to improve software development and security functions. What is the recommended approach to security functions in the DevSecOps process?', '["Complete reliance on cloud service providers for security", "Manual processes to ensure more control", "Strong governance including use of automated tools", "Independent security teams separate from DevOps"]'::jsonb, '[2]'::jsonb, 'DevSecOps integrates security into delivery workflows through governance and automation. Isolated teams and manual-only processes slow feedback and increase inconsistency.', 'medium'),
  (sp4, 'mcq', 'In XYZ Inc., a network administrator provisioned an OCI Load Balancer and views it via the Web GUI. What can the Move Resource feature be used for?', '["To move the Load Balancer to another compartment", "To move the Load Balancer to another region", "To convert the Load Balancer to a Network Load Balancer", "To move the Load Balancer to another subnet"]'::jsonb, '[0]'::jsonb, 'Move Resource changes the compartment that contains the load balancer. It does not convert the service type or move it across regions or subnets.', 'medium'),
  (sp4, 'mcq', 'ABC Inc. requires seamless communication over IPv6 and needs to assign its own IPv6 addresses to resources in OCI. Which OCI service should be used to manage custom IPv6 addresses and provide routing?', '["Oracle Network Path Analyzer", "Oracle Cloud FastConnect", "Oracle Cloud Virtual Network", "Oracle Cloud Load Balancer"]'::jsonb, '[2]'::jsonb, 'A VCN manages IP addressing, subnets, and routing for OCI resources. It is the correct service for custom IPv6 address assignment and routing.', 'medium'),
  (sp4, 'mcq', 'In XYZ Inc., a DevOps team needs to interconnect an on-premises network to OCI resources such as a managed database in a private subnet. The budget and bandwidth requirements are minimal, so VPN is selected. Which OCI object represents the customer router public IP address?', '["Internet Gateway", "Customer Premises Equipment", "IPSec Tunnel", "Virtual Network Interface Card"]'::jsonb, '[1]'::jsonb, 'A CPE object represents the customer-side router in an OCI Site-to-Site VPN configuration. The IPSec tunnels then connect that CPE to the OCI DRG.', 'medium');

  -- Questions for sp5
  INSERT INTO public.questions (subtopic_id, type, question_text, options, correct_answers, explanation, difficulty) VALUES
  (sp5, 'mcq', 'ABC Inc. wants to interconnect OCI with another cloud provider in London so that resources can use ADW machine-learning capabilities. The connection should be quick to provision, high bandwidth, and predictable. Which cloud provider should be chosen?', '["Amazon Web Services", "Google Cloud Platform", "Digital Ocean", "Azure Cloud"]'::jsonb, '[1]'::jsonb, 'The supplied networking course identifies Google Cloud Platform for this OCI interconnection scenario. It meets the stated rapid-provisioning and predictable high-bandwidth requirements.', 'medium'),
  (sp5, 'mcq', 'What is a key difference between Dynamic Routing Gateway and Local Peering Gateway when implementing Cross-Tenancy Peering?', '["Local Peering Gateway can have a Cross-Tenancy Attachment", "Dynamic Routing Gateway can have a Cross-Tenancy Attachment", "Dynamic Routing Gateway needs the acceptor to be in either tenancy", "Local Peering Gateway needs the requestor to be in either tenancy"]'::jsonb, '[1]'::jsonb, 'A DRG supports a cross-tenancy attachment. This is the distinguishing capability identified by the course material.', 'medium'),
  (sp5, 'mcq', 'In Oracle Cloud Infrastructure, which service controls the flow of traffic between different network destinations?', '["Network Security Group associated with a subnet", "Virtual Cloud Network Security List", "Route Table associated with a subnet", "Identity and Access Management"]'::jsonb, '[2]'::jsonb, 'A route table contains rules that direct traffic to network destinations through gateways or other targets. Security lists and NSGs allow or deny traffic but do not choose the route.', 'medium'),
  (sp5, 'mcq', 'Which Oracle Cloud Infrastructure service enables an instance to connect to a Virtual Cloud Network and determines how the instance connects with endpoints inside and outside the VCN?', '["Virtual Network Interface Card", "Internet Gateway", "Route Table", "Network Security Group"]'::jsonb, '[0]'::jsonb, 'A VNIC attaches a compute instance to a VCN. It provides the instance''s network interface and connectivity configuration.', 'medium'),
  (sp5, 'mcq', 'What is the key distinction between stateful and stateless security rules in Oracle Cloud Infrastructure?', '["Stateful rules track the state of network connections while stateless rules do not", "Stateless rules are more secure and provide enhanced encryption", "Stateless rules apply only to inbound traffic while stateful rules apply to both inbound and outbound traffic", "Stateful rules are defined at VCN level while stateless rules are defined at subnet level"]'::jsonb, '[0]'::jsonb, 'Stateful rules automatically account for return traffic by tracking connection state. Stateless rules evaluate each packet independently and require explicit rules for both directions.', 'medium'),
  (sp5, 'mcq', 'As an Autonomous Database administrator, what is the main use of REST APIs?', '["Monitoring", "Monitoring, DevOps", "Monitoring, Development", "Monitoring, DevOps, Development"]'::jsonb, '[3]'::jsonb, 'REST APIs support operational monitoring, automation and DevOps workflows, and application development. The course explicitly lists all three use cases.', 'medium'),
  (sp5, 'mcq', 'Which two statements are true about a cloned Autonomous Database? (Choose two.)', '["It can contain only the metadata of the source Autonomous Database", "It is a refreshable read-write clone of the source Autonomous Database", "It is a refreshable read-only clone of the source Autonomous Database", "It can contain only the data of the source Autonomous Database"]'::jsonb, '[2]'::jsonb, 'The supplied course answer recognizes a refreshable read-only clone and a data-only clone. The read-write and metadata-only statements are not the expected selections.', 'medium'),
  (sp5, 'mcq', 'As an Autonomous Database administrator, what does Database Migration service use for migration?', '["Backup Cloud Module", "RMAN Backup", "GoldenGate", "Data Guard"]'::jsonb, '[2]'::jsonb, 'The course material states that Database Migration service uses GoldenGate. GoldenGate supports replication-based migration with reduced downtime.', 'medium'),
  (sp5, 'mcq', 'Which three actions can you perform from the Autonomous Container Database details page? (Choose three.)', '["Change the maintenance schedule", "Move the CDB to a different compartment", "Change the backup retention policy for the CDB", "Restart the CDB E. Change the maintenance schedule"]'::jsonb, '[1]'::jsonb, 'The verified course selections are moving the CDB, changing its backup retention policy, and restarting it. The screenshot duplicates the maintenance-schedule option, but it is not one of the expected answers.', 'medium'),
  (sp5, 'mcq', 'Which two methods can you use to migrate an on-premises database to Oracle Autonomous Database? (Choose two.)', '["GoldenGate", "RMAN", "Data Pump", "Data Guard"]'::jsonb, '[0]'::jsonb, 'GoldenGate supports replication-based migration, while Data Pump supports logical export and import. RMAN and Data Guard are not the two expected methods for this question.', 'medium'),
  (sp5, 'mcq', 'With which activities does Oracle Machine Learning allow access to data in Autonomous Database?', '["Data ingestion and selection only", "Data ingestion and selection, data viewing and discovery, and data analysis", "Data viewing and discovery, and data ingestion and selection", "Data ingestion and selection, and data viewing and discovery"]'::jsonb, '[1]'::jsonb, 'Oracle Machine Learning supports the full workflow from accessing and selecting data to exploring and analyzing it. The most complete option is therefore correct.', 'medium'),
  (sp5, 'mcq', 'As an Autonomous Database administrator, which statement is true about Spatial Studio?', '["It is a fully managed service available in OCI", "It is a self-service application to create interactive maps", "It does not need additional resources", "It comes with an Autonomous Database at an additional cost"]'::jsonb, '[1]'::jsonb, 'Spatial Studio is a self-service application for visualizing spatial data and building interactive maps. The other descriptions do not match the course definition.', 'medium'),
  (sp5, 'mcq', 'For which three cloud services does DBMS_CLOUD provide support for loading data from files to tables in Autonomous Database? (Choose three.)', '["Amazon AWS S3", "OCI Object Storage Classic", "OCI Object Storage", "Dell EMC Elastic Cloud Storage"]'::jsonb, '[0]'::jsonb, 'DBMS_CLOUD supports Amazon S3, OCI Object Storage Classic, and OCI Object Storage for this loading workflow. Dell EMC Elastic Cloud Storage is not one of the three course answers.', 'medium'),
  (sp5, 'mcq', 'Which statement is true about moving Autonomous Database resources?', '["After a resource is moved to a new tenant, inherent policies apply immediately and affect access", "After a resource is moved to a new compartment, inherent policies apply immediately and affect access", "After a resource is moved to a new tenant, inherent policies apply later and affect access", "After a resource is moved to a new compartment, inherent policies apply later and affect access"]'::jsonb, '[1]'::jsonb, 'When an Autonomous Database resource is moved, the destination compartment''s policies take effect immediately. Access can therefore change as soon as the move completes.', 'medium'),
  (sp5, 'mcq', 'As an Autonomous Database administrator, which procedure do you use to load data directly into existing Autonomous Database tables?', '["DBMS_CLOUD.COPY_DATA", "DBMS_CLOUD.LIST_FILES", "DBMS_CLOUD.PUT_OBJECT", "DBMS_CLOUD.CREATE_EXTERNAL_TABLE"]'::jsonb, '[0]'::jsonb, 'DBMS_CLOUD.COPY_DATA loads data directly into an existing database table. CREATE_EXTERNAL_TABLE instead creates an external table over files.', 'medium');

END $$;
